/plugin install accessibility-architect@devsforge-marketplace
/plugin install api-integration-architect@devsforge-marketplace
/plugin install authentication-specialist@devsforge-marketplace
/plugin install brand-strategist@devsforge-marketplace
/plugin install code-quality-expert@devsforge-marketplace
/plugin install codebase-documenter@devsforge-marketplace
/plugin install compliance-automation-specialist@devsforge-marketplace
/plugin install deployment-engineer@devsforge-marketplace
/plugin install desktop-app-dev@devsforge-marketplace
/plugin install docker-specialist@devsforge-marketplace
/plugin install legal-advisor@devsforge-marketplace
/plugin install localization-specialist@devsforge-marketplace
/plugin install mobile-app-builder@devsforge-marketplace
/plugin install project-shipper@devsforge-marketplace
/plugin install project-curator@devsforge-marketplace
/plugin install release-coordinator@devsforge-marketplace
/plugin install trend-researcher@devsforge-marketplace
/plugin install ui-ux-engineer@devsforge-marketplace
/plugin install ux-researcher@devsforge-marketplace
/plugin install web-dev@devsforge-marketplace
/plugin install code-review-assistant@devsforge-marketplace
/plugin install performance-profiler@devsforge-marketplace
/plugin install robots-txt-generator@devsforge-marketplace
/plugin install security-auditor@devsforge-marketplace
/plugin install security-scanner@devsforge-marketplace
