import { prisma } from '../lib/prisma';
import type { ExerciseCategory, WorkoutDifficulty } from '@prisma/client';

export interface ExerciseCatalogEntry {
  key: string;
  name: string;
  category: ExerciseCategory;
  difficulty: WorkoutDifficulty;
  defaultSets: number;
  defaultRepsMin: number;
  defaultRepsMax: number;
  defaultRestSeconds: number;
  instructions?: string;
  tags: string[];
}

export const EXERCISE_CATALOG: ExerciseCatalogEntry[] = [
  {
    key: 'BODYWEIGHT_SQUAT_BEGINNER',
    name: 'Bodyweight Squat',
    category: 'STRENGTH',
    difficulty: 'BEGINNER',
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 15,
    defaultRestSeconds: 60,
    instructions: 'Stand tall, sit hips back, keep chest proud, then drive up through heels.',
    tags: ['legs', 'lower-body', 'bodyweight', 'foundational'],
  },
  {
    key: 'GLUTE_BRIDGE_BEGINNER',
    name: 'Glute Bridge',
    category: 'STRENGTH',
    difficulty: 'BEGINNER',
    defaultSets: 3,
    defaultRepsMin: 12,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    instructions: 'Press through heels and squeeze glutes at the top without arching lower back.',
    tags: ['glutes', 'posterior-chain', 'bodyweight'],
  },
  {
    key: 'KNEE_PUSHUP_BEGINNER',
    name: 'Knee Push-Up',
    category: 'STRENGTH',
    difficulty: 'BEGINNER',
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 60,
    instructions: 'Keep a straight line from knees to shoulders and lower chest with control.',
    tags: ['upper-body', 'chest', 'bodyweight'],
  },
  {
    key: 'DUMBBELL_GOBLET_SQUAT_INTERMEDIATE',
    name: 'Dumbbell Goblet Squat',
    category: 'STRENGTH',
    difficulty: 'INTERMEDIATE',
    defaultSets: 4,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 75,
    instructions: 'Hold dumbbell at chest, keep elbows down, and squat to a comfortable depth.',
    tags: ['legs', 'strength', 'dumbbell'],
  },
  {
    key: 'DUMBBELL_ROMANIAN_DEADLIFT_INTERMEDIATE',
    name: 'Dumbbell Romanian Deadlift',
    category: 'STRENGTH',
    difficulty: 'INTERMEDIATE',
    defaultSets: 4,
    defaultRepsMin: 8,
    defaultRepsMax: 10,
    defaultRestSeconds: 90,
    instructions: 'Hinge at hips with neutral spine and keep dumbbells close to your legs.',
    tags: ['hamstrings', 'glutes', 'strength', 'dumbbell'],
  },
  {
    key: 'BARBELL_BACK_SQUAT_ADVANCED',
    name: 'Barbell Back Squat',
    category: 'STRENGTH',
    difficulty: 'ADVANCED',
    defaultSets: 5,
    defaultRepsMin: 4,
    defaultRepsMax: 6,
    defaultRestSeconds: 120,
    instructions: 'Brace core, keep bar path over mid-foot, and drive out of the hole with control.',
    tags: ['barbell', 'compound', 'strength', 'legs'],
  },
  {
    key: 'BARBELL_DEADLIFT_ADVANCED',
    name: 'Barbell Deadlift',
    category: 'STRENGTH',
    difficulty: 'ADVANCED',
    defaultSets: 5,
    defaultRepsMin: 3,
    defaultRepsMax: 5,
    defaultRestSeconds: 150,
    instructions: 'Set lats, push floor away, and lock out with glutes without leaning back.',
    tags: ['barbell', 'posterior-chain', 'compound'],
  },
  {
    key: 'WALKING_CARDIO_BEGINNER',
    name: 'Brisk Walk',
    category: 'CARDIO',
    difficulty: 'BEGINNER',
    defaultSets: 1,
    defaultRepsMin: 15,
    defaultRepsMax: 25,
    defaultRestSeconds: 0,
    instructions: 'Maintain a pace that elevates breathing while still allowing short conversation.',
    tags: ['low-impact', 'endurance', 'outdoor'],
  },
  {
    key: 'STATIONARY_BIKE_BEGINNER',
    name: 'Stationary Bike',
    category: 'CARDIO',
    difficulty: 'BEGINNER',
    defaultSets: 1,
    defaultRepsMin: 12,
    defaultRepsMax: 20,
    defaultRestSeconds: 0,
    instructions: 'Keep cadence steady and maintain moderate resistance.',
    tags: ['low-impact', 'indoor', 'endurance'],
  },
  {
    key: 'ROWERG_INTERVALS_INTERMEDIATE',
    name: 'Rower Intervals',
    category: 'CARDIO',
    difficulty: 'INTERMEDIATE',
    defaultSets: 5,
    defaultRepsMin: 2,
    defaultRepsMax: 3,
    defaultRestSeconds: 60,
    instructions: 'Alternate hard rowing intervals with easy recovery paddles.',
    tags: ['intervals', 'indoor', 'full-body'],
  },
  {
    key: 'TREADMILL_TEMPO_INTERMEDIATE',
    name: 'Treadmill Tempo Run',
    category: 'CARDIO',
    difficulty: 'INTERMEDIATE',
    defaultSets: 1,
    defaultRepsMin: 20,
    defaultRepsMax: 30,
    defaultRestSeconds: 0,
    instructions: 'Run at comfortably hard pace you can sustain for the full set.',
    tags: ['running', 'tempo', 'endurance'],
  },
  {
    key: 'ASSAULT_BIKE_SPRINT_ADVANCED',
    name: 'Assault Bike Sprints',
    category: 'CARDIO',
    difficulty: 'ADVANCED',
    defaultSets: 8,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
    defaultRestSeconds: 75,
    instructions: 'Sprint at max effort for work interval, then recover fully before next effort.',
    tags: ['sprints', 'high-intensity', 'conditioning'],
  },
  {
    key: 'BURPEE_INTERVAL_ADVANCED',
    name: 'Burpee Intervals',
    category: 'CARDIO',
    difficulty: 'ADVANCED',
    defaultSets: 6,
    defaultRepsMin: 10,
    defaultRepsMax: 15,
    defaultRestSeconds: 75,
    instructions: 'Move explosively while keeping a neutral spine on the plank phase.',
    tags: ['bodyweight', 'conditioning', 'high-intensity'],
  },
  {
    key: 'CAT_COW_BEGINNER',
    name: 'Cat-Cow Flow',
    category: 'MOBILITY',
    difficulty: 'BEGINNER',
    defaultSets: 2,
    defaultRepsMin: 8,
    defaultRepsMax: 10,
    defaultRestSeconds: 30,
    instructions: 'Move slowly with breath, rounding and extending the spine gently.',
    tags: ['spine', 'warmup', 'mobility'],
  },
  {
    key: 'HIP_OPENERS_BEGINNER',
    name: 'Hip Openers',
    category: 'MOBILITY',
    difficulty: 'BEGINNER',
    defaultSets: 2,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 30,
    instructions: 'Controlled dynamic range of motion focusing on hips and groin.',
    tags: ['hips', 'warmup', 'mobility'],
  },
  {
    key: 'WORLD_GREATEST_STRETCH_INTERMEDIATE',
    name: 'World’s Greatest Stretch',
    category: 'MOBILITY',
    difficulty: 'INTERMEDIATE',
    defaultSets: 2,
    defaultRepsMin: 5,
    defaultRepsMax: 8,
    defaultRestSeconds: 30,
    instructions: 'Step into lunge, rotate thoracic spine, then alternate sides.',
    tags: ['full-body', 'dynamic', 'mobility'],
  },
  {
    key: 'COSSACK_SQUAT_INTERMEDIATE',
    name: 'Cossack Squat Mobility',
    category: 'MOBILITY',
    difficulty: 'INTERMEDIATE',
    defaultSets: 3,
    defaultRepsMin: 6,
    defaultRepsMax: 8,
    defaultRestSeconds: 45,
    instructions: 'Shift side to side with control and maintain heel contact where possible.',
    tags: ['hips', 'adductors', 'mobility'],
  },
  {
    key: 'OVERHEAD_SQUAT_HOLD_ADVANCED',
    name: 'Overhead Squat Hold',
    category: 'MOBILITY',
    difficulty: 'ADVANCED',
    defaultSets: 4,
    defaultRepsMin: 20,
    defaultRepsMax: 30,
    defaultRestSeconds: 45,
    instructions: 'Hold stable overhead position with ribs down and knees tracking over toes.',
    tags: ['shoulders', 'ankles', 'thoracic', 'mobility'],
  },
  {
    key: 'PIKE_COMPRESSION_ADVANCED',
    name: 'Pike Compression Pulses',
    category: 'MOBILITY',
    difficulty: 'ADVANCED',
    defaultSets: 3,
    defaultRepsMin: 10,
    defaultRepsMax: 15,
    defaultRestSeconds: 45,
    instructions: 'Stay tall through spine and drive active compression from hip flexors.',
    tags: ['hamstrings', 'core', 'mobility'],
  },
  {
    key: 'HAMSTRING_STRETCH_BEGINNER',
    name: 'Supine Hamstring Stretch',
    category: 'FLEXIBILITY',
    difficulty: 'BEGINNER',
    defaultSets: 2,
    defaultRepsMin: 30,
    defaultRepsMax: 45,
    defaultRestSeconds: 20,
    instructions: 'Keep opposite leg grounded and breathe slowly into the stretch.',
    tags: ['hamstrings', 'stretching', 'cooldown'],
  },
  {
    key: 'CHEST_STRETCH_BEGINNER',
    name: 'Doorway Chest Stretch',
    category: 'FLEXIBILITY',
    difficulty: 'BEGINNER',
    defaultSets: 2,
    defaultRepsMin: 25,
    defaultRepsMax: 40,
    defaultRestSeconds: 20,
    instructions: 'Step through doorway gently until mild stretch in chest and shoulders.',
    tags: ['chest', 'shoulders', 'posture'],
  },
  {
    key: 'PNF_HAMSTRING_INTERMEDIATE',
    name: 'PNF Hamstring Stretch',
    category: 'FLEXIBILITY',
    difficulty: 'INTERMEDIATE',
    defaultSets: 3,
    defaultRepsMin: 20,
    defaultRepsMax: 30,
    defaultRestSeconds: 30,
    instructions: 'Contract hamstrings for 5 seconds, then relax deeper into stretch.',
    tags: ['pnf', 'hamstrings', 'flexibility'],
  },
  {
    key: 'SEATED_STRADDLE_INTERMEDIATE',
    name: 'Seated Straddle Fold',
    category: 'FLEXIBILITY',
    difficulty: 'INTERMEDIATE',
    defaultSets: 3,
    defaultRepsMin: 25,
    defaultRepsMax: 40,
    defaultRestSeconds: 25,
    instructions: 'Hinge from hips and keep long spine while folding forward.',
    tags: ['adductors', 'hamstrings', 'flexibility'],
  },
  {
    key: 'FRONT_SPLIT_PREP_ADVANCED',
    name: 'Front Split Prep',
    category: 'FLEXIBILITY',
    difficulty: 'ADVANCED',
    defaultSets: 4,
    defaultRepsMin: 30,
    defaultRepsMax: 45,
    defaultRestSeconds: 30,
    instructions: 'Use blocks for support and maintain square hips as you lower.',
    tags: ['splits', 'hip-flexors', 'hamstrings'],
  },
  {
    key: 'SHOULDER_BRIDGE_ADVANCED',
    name: 'Shoulder Bridge Flexibility',
    category: 'FLEXIBILITY',
    difficulty: 'ADVANCED',
    defaultSets: 3,
    defaultRepsMin: 15,
    defaultRepsMax: 25,
    defaultRestSeconds: 45,
    instructions: 'Open shoulders and thoracic spine while keeping controlled breath.',
    tags: ['thoracic', 'shoulders', 'backbend'],
  },
  {
    key: 'BOX_BREATHING_BEGINNER',
    name: 'Box Breathing',
    category: 'RECOVERY',
    difficulty: 'BEGINNER',
    defaultSets: 3,
    defaultRepsMin: 60,
    defaultRepsMax: 90,
    defaultRestSeconds: 15,
    instructions: 'Inhale 4 sec, hold 4 sec, exhale 4 sec, hold 4 sec in a steady loop.',
    tags: ['breathing', 'nervous-system', 'recovery'],
  },
  {
    key: 'WALK_COOLDOWN_BEGINNER',
    name: 'Cooldown Walk',
    category: 'RECOVERY',
    difficulty: 'BEGINNER',
    defaultSets: 1,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 0,
    instructions: 'Keep pace easy and focus on returning breathing to baseline.',
    tags: ['cooldown', 'low-intensity', 'recovery'],
  },
  {
    key: 'FOAM_ROLL_FULL_BODY_INTERMEDIATE',
    name: 'Full-Body Foam Rolling',
    category: 'RECOVERY',
    difficulty: 'INTERMEDIATE',
    defaultSets: 1,
    defaultRepsMin: 10,
    defaultRepsMax: 15,
    defaultRestSeconds: 0,
    instructions: 'Spend 30-60 seconds per major muscle group, pausing on tight spots.',
    tags: ['soft-tissue', 'mobility', 'recovery'],
  },
  {
    key: 'CONTRAST_SHOWER_INTERMEDIATE',
    name: 'Contrast Shower Recovery',
    category: 'RECOVERY',
    difficulty: 'INTERMEDIATE',
    defaultSets: 4,
    defaultRepsMin: 1,
    defaultRepsMax: 2,
    defaultRestSeconds: 30,
    instructions: 'Alternate warm and cool water cycles to support post-session recovery.',
    tags: ['recovery', 'circulation'],
  },
  {
    key: 'NSDR_PROTOCOL_ADVANCED',
    name: 'NSDR Recovery Protocol',
    category: 'RECOVERY',
    difficulty: 'ADVANCED',
    defaultSets: 1,
    defaultRepsMin: 10,
    defaultRepsMax: 20,
    defaultRestSeconds: 0,
    instructions: 'Follow a guided Non-Sleep Deep Rest sequence in a quiet environment.',
    tags: ['breathwork', 'mindfulness', 'recovery'],
  },
  {
    key: 'ACTIVE_RECOVERY_CIRCUIT_ADVANCED',
    name: 'Active Recovery Circuit',
    category: 'RECOVERY',
    difficulty: 'ADVANCED',
    defaultSets: 3,
    defaultRepsMin: 8,
    defaultRepsMax: 12,
    defaultRestSeconds: 45,
    instructions: 'Low-load movement circuit focused on blood flow and technique quality.',
    tags: ['low-load', 'recovery', 'full-body'],
  },
];

export async function seedExerciseCatalog(): Promise<void> {
  console.log(`   Seeding ${EXERCISE_CATALOG.length} exercise catalog entries...`);

  let created = 0;
  let updated = 0;

  for (const entry of EXERCISE_CATALOG) {
    const existing = await prisma.exerciseCatalog.findUnique({ where: { key: entry.key } });

    await prisma.exerciseCatalog.upsert({
      where: { key: entry.key },
      update: {
        name: entry.name,
        category: entry.category,
        difficulty: entry.difficulty,
        defaultSets: entry.defaultSets,
        defaultRepsMin: entry.defaultRepsMin,
        defaultRepsMax: entry.defaultRepsMax,
        defaultRestSeconds: entry.defaultRestSeconds,
        instructions: entry.instructions,
        tags: entry.tags,
        isActive: true,
      },
      create: {
        key: entry.key,
        name: entry.name,
        category: entry.category,
        difficulty: entry.difficulty,
        defaultSets: entry.defaultSets,
        defaultRepsMin: entry.defaultRepsMin,
        defaultRepsMax: entry.defaultRepsMax,
        defaultRestSeconds: entry.defaultRestSeconds,
        instructions: entry.instructions,
        tags: entry.tags,
        isActive: true,
      },
    });

    if (existing) {
      updated++;
    } else {
      created++;
    }
  }

  console.log(`   ✓ Exercise catalog: ${created} created, ${updated} updated`);
}
