/**
 * First Aid Data
 * Comprehensive first aid procedures based on Red Cross and medical guidelines
 * 
 * DISCLAIMER: This information is for educational purposes only.
 * Always call emergency services in life-threatening situations.
 */

import { FirstAidCard, EmergencyNumber, Helpline } from './first-aid.types';

export const FIRST_AID_CARDS: FirstAidCard[] = [
  // =============== CPR ===============
  {
    id: 'cpr-adult',
    category: 'cpr',
    titleKey: 'FIRST_AID.CPR_ADULT.TITLE',
    descriptionKey: 'FIRST_AID.CPR_ADULT.DESC',
    icon: '❤️',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.CPR_ADULT.STEP_1', warning: 'FIRST_AID.CPR_ADULT.STEP_1_WARN' },
      { order: 2, instruction: 'FIRST_AID.CPR_ADULT.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.CPR_ADULT.STEP_3', tip: 'FIRST_AID.CPR_ADULT.STEP_3_TIP' },
      { order: 4, instruction: 'FIRST_AID.CPR_ADULT.STEP_4', duration: '30 compressions' },
      { order: 5, instruction: 'FIRST_AID.CPR_ADULT.STEP_5' },
      { order: 6, instruction: 'FIRST_AID.CPR_ADULT.STEP_6' },
    ],
    warnings: ['FIRST_AID.CPR_ADULT.WARN_1', 'FIRST_AID.CPR_ADULT.WARN_2'],
    whenToCallEmergency: ['FIRST_AID.CPR_ADULT.CALL_1'],
    doNot: ['FIRST_AID.CPR_ADULT.DONOT_1', 'FIRST_AID.CPR_ADULT.DONOT_2'],
    relatedCards: ['choking-adult', 'heart-attack'],
  },

  // =============== CHOKING ===============
  {
    id: 'choking-adult',
    category: 'choking',
    titleKey: 'FIRST_AID.CHOKING_ADULT.TITLE',
    descriptionKey: 'FIRST_AID.CHOKING_ADULT.DESC',
    icon: '🫁',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.CHOKING_ADULT.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.CHOKING_ADULT.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.CHOKING_ADULT.STEP_3', tip: 'FIRST_AID.CHOKING_ADULT.STEP_3_TIP' },
      { order: 4, instruction: 'FIRST_AID.CHOKING_ADULT.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.CHOKING_ADULT.STEP_5' },
    ],
    warnings: ['FIRST_AID.CHOKING_ADULT.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.CHOKING_ADULT.CALL_1'],
    doNot: ['FIRST_AID.CHOKING_ADULT.DONOT_1'],
    relatedCards: ['cpr-adult'],
  },
  {
    id: 'choking-infant',
    category: 'choking',
    titleKey: 'FIRST_AID.CHOKING_INFANT.TITLE',
    descriptionKey: 'FIRST_AID.CHOKING_INFANT.DESC',
    icon: '👶',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.CHOKING_INFANT.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.CHOKING_INFANT.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.CHOKING_INFANT.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.CHOKING_INFANT.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.CHOKING_INFANT.STEP_5' },
    ],
    warnings: ['FIRST_AID.CHOKING_INFANT.WARN_1', 'FIRST_AID.CHOKING_INFANT.WARN_2'],
    whenToCallEmergency: ['FIRST_AID.CHOKING_INFANT.CALL_1'],
    doNot: ['FIRST_AID.CHOKING_INFANT.DONOT_1'],
  },

  // =============== BURNS ===============
  {
    id: 'burns-minor',
    category: 'burns',
    titleKey: 'FIRST_AID.BURNS_MINOR.TITLE',
    descriptionKey: 'FIRST_AID.BURNS_MINOR.DESC',
    icon: '🔥',
    severity: 'moderate',
    steps: [
      { order: 1, instruction: 'FIRST_AID.BURNS_MINOR.STEP_1', duration: '10-20 minutes' },
      { order: 2, instruction: 'FIRST_AID.BURNS_MINOR.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.BURNS_MINOR.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.BURNS_MINOR.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.BURNS_MINOR.STEP_5' },
    ],
    warnings: ['FIRST_AID.BURNS_MINOR.WARN_1'],
    doNot: ['FIRST_AID.BURNS_MINOR.DONOT_1', 'FIRST_AID.BURNS_MINOR.DONOT_2', 'FIRST_AID.BURNS_MINOR.DONOT_3'],
    relatedCards: ['burns-severe'],
  },
  {
    id: 'burns-severe',
    category: 'burns',
    titleKey: 'FIRST_AID.BURNS_SEVERE.TITLE',
    descriptionKey: 'FIRST_AID.BURNS_SEVERE.DESC',
    icon: '🚨',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.BURNS_SEVERE.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.BURNS_SEVERE.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.BURNS_SEVERE.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.BURNS_SEVERE.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.BURNS_SEVERE.STEP_5' },
    ],
    warnings: ['FIRST_AID.BURNS_SEVERE.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.BURNS_SEVERE.CALL_1'],
    doNot: ['FIRST_AID.BURNS_SEVERE.DONOT_1', 'FIRST_AID.BURNS_SEVERE.DONOT_2', 'FIRST_AID.BURNS_SEVERE.DONOT_3'],
    relatedCards: ['burns-minor', 'shock'],
  },

  // =============== ALLERGIC REACTIONS ===============
  {
    id: 'allergic-mild',
    category: 'allergic-reactions',
    titleKey: 'FIRST_AID.ALLERGIC_MILD.TITLE',
    descriptionKey: 'FIRST_AID.ALLERGIC_MILD.DESC',
    icon: '🤧',
    severity: 'moderate',
    steps: [
      { order: 1, instruction: 'FIRST_AID.ALLERGIC_MILD.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.ALLERGIC_MILD.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.ALLERGIC_MILD.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.ALLERGIC_MILD.STEP_4' },
    ],
    warnings: ['FIRST_AID.ALLERGIC_MILD.WARN_1'],
    relatedCards: ['anaphylaxis'],
  },
  {
    id: 'anaphylaxis',
    category: 'allergic-reactions',
    titleKey: 'FIRST_AID.ANAPHYLAXIS.TITLE',
    descriptionKey: 'FIRST_AID.ANAPHYLAXIS.DESC',
    icon: '💉',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.ANAPHYLAXIS.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.ANAPHYLAXIS.STEP_2', tip: 'FIRST_AID.ANAPHYLAXIS.STEP_2_TIP' },
      { order: 3, instruction: 'FIRST_AID.ANAPHYLAXIS.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.ANAPHYLAXIS.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.ANAPHYLAXIS.STEP_5' },
    ],
    warnings: ['FIRST_AID.ANAPHYLAXIS.WARN_1', 'FIRST_AID.ANAPHYLAXIS.WARN_2'],
    whenToCallEmergency: ['FIRST_AID.ANAPHYLAXIS.CALL_1'],
    doNot: ['FIRST_AID.ANAPHYLAXIS.DONOT_1'],
    relatedCards: ['allergic-mild', 'shock'],
  },

  // =============== FRACTURES ===============
  {
    id: 'fracture-limb',
    category: 'fractures',
    titleKey: 'FIRST_AID.FRACTURE_LIMB.TITLE',
    descriptionKey: 'FIRST_AID.FRACTURE_LIMB.DESC',
    icon: '🦴',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'FIRST_AID.FRACTURE_LIMB.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.FRACTURE_LIMB.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.FRACTURE_LIMB.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.FRACTURE_LIMB.STEP_4', tip: 'FIRST_AID.FRACTURE_LIMB.STEP_4_TIP' },
      { order: 5, instruction: 'FIRST_AID.FRACTURE_LIMB.STEP_5' },
    ],
    warnings: ['FIRST_AID.FRACTURE_LIMB.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.FRACTURE_LIMB.CALL_1'],
    doNot: ['FIRST_AID.FRACTURE_LIMB.DONOT_1', 'FIRST_AID.FRACTURE_LIMB.DONOT_2'],
    relatedCards: ['fracture-spine', 'shock'],
  },
  {
    id: 'fracture-spine',
    category: 'fractures',
    titleKey: 'FIRST_AID.FRACTURE_SPINE.TITLE',
    descriptionKey: 'FIRST_AID.FRACTURE_SPINE.DESC',
    icon: '⚠️',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.FRACTURE_SPINE.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.FRACTURE_SPINE.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.FRACTURE_SPINE.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.FRACTURE_SPINE.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.FRACTURE_SPINE.STEP_5' },
    ],
    warnings: ['FIRST_AID.FRACTURE_SPINE.WARN_1', 'FIRST_AID.FRACTURE_SPINE.WARN_2'],
    whenToCallEmergency: ['FIRST_AID.FRACTURE_SPINE.CALL_1'],
    doNot: ['FIRST_AID.FRACTURE_SPINE.DONOT_1', 'FIRST_AID.FRACTURE_SPINE.DONOT_2', 'FIRST_AID.FRACTURE_SPINE.DONOT_3'],
    relatedCards: ['fracture-limb'],
  },

  // =============== BLEEDING ===============
  {
    id: 'bleeding-minor',
    category: 'bleeding',
    titleKey: 'FIRST_AID.BLEEDING_MINOR.TITLE',
    descriptionKey: 'FIRST_AID.BLEEDING_MINOR.DESC',
    icon: '🩹',
    severity: 'minor',
    steps: [
      { order: 1, instruction: 'FIRST_AID.BLEEDING_MINOR.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.BLEEDING_MINOR.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.BLEEDING_MINOR.STEP_3', duration: '10-15 minutes' },
      { order: 4, instruction: 'FIRST_AID.BLEEDING_MINOR.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.BLEEDING_MINOR.STEP_5' },
    ],
    doNot: ['FIRST_AID.BLEEDING_MINOR.DONOT_1'],
    relatedCards: ['bleeding-severe'],
  },
  {
    id: 'bleeding-severe',
    category: 'bleeding',
    titleKey: 'FIRST_AID.BLEEDING_SEVERE.TITLE',
    descriptionKey: 'FIRST_AID.BLEEDING_SEVERE.DESC',
    icon: '🩸',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.BLEEDING_SEVERE.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.BLEEDING_SEVERE.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.BLEEDING_SEVERE.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.BLEEDING_SEVERE.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.BLEEDING_SEVERE.STEP_5' },
    ],
    warnings: ['FIRST_AID.BLEEDING_SEVERE.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.BLEEDING_SEVERE.CALL_1'],
    doNot: ['FIRST_AID.BLEEDING_SEVERE.DONOT_1', 'FIRST_AID.BLEEDING_SEVERE.DONOT_2'],
    relatedCards: ['bleeding-minor', 'shock'],
  },

  // =============== HEART ATTACK ===============
  {
    id: 'heart-attack',
    category: 'heart-attack',
    titleKey: 'FIRST_AID.HEART_ATTACK.TITLE',
    descriptionKey: 'FIRST_AID.HEART_ATTACK.DESC',
    icon: '💔',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.HEART_ATTACK.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.HEART_ATTACK.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.HEART_ATTACK.STEP_3', tip: 'FIRST_AID.HEART_ATTACK.STEP_3_TIP' },
      { order: 4, instruction: 'FIRST_AID.HEART_ATTACK.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.HEART_ATTACK.STEP_5' },
    ],
    warnings: ['FIRST_AID.HEART_ATTACK.WARN_1', 'FIRST_AID.HEART_ATTACK.WARN_2'],
    whenToCallEmergency: ['FIRST_AID.HEART_ATTACK.CALL_1'],
    doNot: ['FIRST_AID.HEART_ATTACK.DONOT_1'],
    relatedCards: ['cpr-adult', 'stroke'],
  },

  // =============== STROKE ===============
  {
    id: 'stroke',
    category: 'stroke',
    titleKey: 'FIRST_AID.STROKE.TITLE',
    descriptionKey: 'FIRST_AID.STROKE.DESC',
    icon: '🧠',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.STROKE.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.STROKE.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.STROKE.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.STROKE.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.STROKE.STEP_5' },
    ],
    warnings: ['FIRST_AID.STROKE.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.STROKE.CALL_1'],
    doNot: ['FIRST_AID.STROKE.DONOT_1', 'FIRST_AID.STROKE.DONOT_2'],
    relatedCards: ['heart-attack'],
  },

  // =============== SHOCK ===============
  {
    id: 'shock',
    category: 'shock',
    titleKey: 'FIRST_AID.SHOCK.TITLE',
    descriptionKey: 'FIRST_AID.SHOCK.DESC',
    icon: '😰',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.SHOCK.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.SHOCK.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.SHOCK.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.SHOCK.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.SHOCK.STEP_5' },
    ],
    warnings: ['FIRST_AID.SHOCK.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.SHOCK.CALL_1'],
    doNot: ['FIRST_AID.SHOCK.DONOT_1', 'FIRST_AID.SHOCK.DONOT_2'],
    relatedCards: ['bleeding-severe', 'burns-severe'],
  },

  // =============== SEIZURES ===============
  {
    id: 'seizures',
    category: 'seizures',
    titleKey: 'FIRST_AID.SEIZURES.TITLE',
    descriptionKey: 'FIRST_AID.SEIZURES.DESC',
    icon: '⚡',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'FIRST_AID.SEIZURES.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.SEIZURES.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.SEIZURES.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.SEIZURES.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.SEIZURES.STEP_5' },
    ],
    warnings: ['FIRST_AID.SEIZURES.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.SEIZURES.CALL_1', 'FIRST_AID.SEIZURES.CALL_2'],
    doNot: ['FIRST_AID.SEIZURES.DONOT_1', 'FIRST_AID.SEIZURES.DONOT_2', 'FIRST_AID.SEIZURES.DONOT_3'],
  },

  // =============== POISONING ===============
  {
    id: 'poisoning',
    category: 'poisoning',
    titleKey: 'FIRST_AID.POISONING.TITLE',
    descriptionKey: 'FIRST_AID.POISONING.DESC',
    icon: '☠️',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.POISONING.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.POISONING.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.POISONING.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.POISONING.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.POISONING.STEP_5' },
    ],
    warnings: ['FIRST_AID.POISONING.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.POISONING.CALL_1'],
    doNot: ['FIRST_AID.POISONING.DONOT_1', 'FIRST_AID.POISONING.DONOT_2', 'FIRST_AID.POISONING.DONOT_3'],
  },

  // =============== HYPOTHERMIA ===============
  {
    id: 'hypothermia',
    category: 'hypothermia',
    titleKey: 'FIRST_AID.HYPOTHERMIA.TITLE',
    descriptionKey: 'FIRST_AID.HYPOTHERMIA.DESC',
    icon: '🥶',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'FIRST_AID.HYPOTHERMIA.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.HYPOTHERMIA.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.HYPOTHERMIA.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.HYPOTHERMIA.STEP_4', tip: 'FIRST_AID.HYPOTHERMIA.STEP_4_TIP' },
      { order: 5, instruction: 'FIRST_AID.HYPOTHERMIA.STEP_5' },
    ],
    warnings: ['FIRST_AID.HYPOTHERMIA.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.HYPOTHERMIA.CALL_1'],
    doNot: ['FIRST_AID.HYPOTHERMIA.DONOT_1', 'FIRST_AID.HYPOTHERMIA.DONOT_2'],
    relatedCards: ['heat-stroke'],
  },

  // =============== HEAT STROKE ===============
  {
    id: 'heat-stroke',
    category: 'heat-stroke',
    titleKey: 'FIRST_AID.HEAT_STROKE.TITLE',
    descriptionKey: 'FIRST_AID.HEAT_STROKE.DESC',
    icon: '🥵',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.HEAT_STROKE.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.HEAT_STROKE.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.HEAT_STROKE.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.HEAT_STROKE.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.HEAT_STROKE.STEP_5' },
    ],
    warnings: ['FIRST_AID.HEAT_STROKE.WARN_1', 'FIRST_AID.HEAT_STROKE.WARN_2'],
    whenToCallEmergency: ['FIRST_AID.HEAT_STROKE.CALL_1'],
    doNot: ['FIRST_AID.HEAT_STROKE.DONOT_1', 'FIRST_AID.HEAT_STROKE.DONOT_2'],
    relatedCards: ['hypothermia'],
  },

  // =============== BITES & STINGS ===============
  {
    id: 'bee-sting',
    category: 'bites-stings',
    titleKey: 'FIRST_AID.BEE_STING.TITLE',
    descriptionKey: 'FIRST_AID.BEE_STING.DESC',
    icon: '🐝',
    severity: 'moderate',
    steps: [
      { order: 1, instruction: 'FIRST_AID.BEE_STING.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.BEE_STING.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.BEE_STING.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.BEE_STING.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.BEE_STING.STEP_5' },
    ],
    warnings: ['FIRST_AID.BEE_STING.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.BEE_STING.CALL_1'],
    doNot: ['FIRST_AID.BEE_STING.DONOT_1'],
    relatedCards: ['anaphylaxis', 'snake-bite'],
  },
  {
    id: 'snake-bite',
    category: 'bites-stings',
    titleKey: 'FIRST_AID.SNAKE_BITE.TITLE',
    descriptionKey: 'FIRST_AID.SNAKE_BITE.DESC',
    icon: '🐍',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.SNAKE_BITE.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.SNAKE_BITE.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.SNAKE_BITE.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.SNAKE_BITE.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.SNAKE_BITE.STEP_5' },
    ],
    warnings: ['FIRST_AID.SNAKE_BITE.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.SNAKE_BITE.CALL_1'],
    doNot: ['FIRST_AID.SNAKE_BITE.DONOT_1', 'FIRST_AID.SNAKE_BITE.DONOT_2', 'FIRST_AID.SNAKE_BITE.DONOT_3'],
    relatedCards: ['bee-sting', 'shock'],
  },

  // =============== DROWNING ===============
  {
    id: 'drowning',
    category: 'drowning',
    titleKey: 'FIRST_AID.DROWNING.TITLE',
    descriptionKey: 'FIRST_AID.DROWNING.DESC',
    icon: '🌊',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.DROWNING.STEP_1', warning: 'FIRST_AID.DROWNING.STEP_1_WARN' },
      { order: 2, instruction: 'FIRST_AID.DROWNING.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.DROWNING.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.DROWNING.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.DROWNING.STEP_5' },
    ],
    warnings: ['FIRST_AID.DROWNING.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.DROWNING.CALL_1'],
    doNot: ['FIRST_AID.DROWNING.DONOT_1'],
    relatedCards: ['cpr-adult', 'hypothermia'],
  },

  // =============== EXTENDED FIRST AID LIBRARY ===============
  {
    id: 'nosebleed',
    category: 'bleeding',
    titleKey: 'Nosebleed',
    descriptionKey: 'Control common nosebleeds safely at home.',
    icon: '👃',
    severity: 'minor',
    steps: [
      { order: 1, instruction: 'Sit upright and lean slightly forward.' },
      { order: 2, instruction: 'Pinch the soft part of the nose for 10 minutes.' },
      { order: 3, instruction: 'Apply a cold pack over the bridge of the nose.' },
    ],
    warnings: ['Heavy bleeding can become serious quickly.'],
    whenToCallEmergency: ['Call if bleeding lasts more than 20 minutes or follows major trauma.'],
    doNot: ['Do not tilt the head backward.'],
    relatedCards: ['bleeding-severe'],
  },
  {
    id: 'fainting',
    category: 'shock',
    titleKey: 'Fainting',
    descriptionKey: 'Immediate steps when someone faints or nearly faints.',
    icon: '😵',
    severity: 'moderate',
    steps: [
      { order: 1, instruction: 'Lay the person flat and raise legs if possible.' },
      { order: 2, instruction: 'Loosen tight clothing and ensure fresh air.' },
      { order: 3, instruction: 'Check breathing and responsiveness continuously.' },
    ],
    warnings: ['Fainting can signal heart, stroke, or bleeding problems.'],
    whenToCallEmergency: ['Call if consciousness does not return within 1 minute.'],
    doNot: ['Do not force food or drink immediately.'],
    relatedCards: ['shock'],
  },
  {
    id: 'asthma-attack',
    category: 'choking',
    titleKey: 'Asthma Attack',
    descriptionKey: 'Support breathing during a sudden asthma flare.',
    icon: '🫁',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'Help the person sit upright and stay calm.' },
      { order: 2, instruction: 'Assist with rescue inhaler use as prescribed.' },
      { order: 3, instruction: 'Repeat inhaler doses per action plan while monitoring.' },
    ],
    warnings: ['Severe wheezing and silent chest are red flags.'],
    whenToCallEmergency: ['Call if symptoms do not improve quickly or speech is difficult.'],
    doNot: ['Do not have the person lie flat.'],
  },
  {
    id: 'hypoglycemia',
    category: 'shock',
    titleKey: 'Low Blood Sugar',
    descriptionKey: 'Fast treatment for suspected hypoglycemia.',
    icon: '🍬',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'Give 15 grams of fast sugar if the person is awake.' },
      { order: 2, instruction: 'Recheck symptoms after 15 minutes and repeat if needed.' },
      { order: 3, instruction: 'Follow with a snack containing carbs and protein.' },
    ],
    warnings: ['Untreated low blood sugar can cause seizure or coma.'],
    whenToCallEmergency: ['Call if the person is confused, unconscious, or cannot swallow.'],
    doNot: ['Do not give food or drink to an unconscious person.'],
  },
  {
    id: 'hyperglycemia',
    category: 'shock',
    titleKey: 'High Blood Sugar Crisis',
    descriptionKey: 'First aid for dangerous high blood sugar symptoms.',
    icon: '🩸',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'Help the person rest and drink water if alert.' },
      { order: 2, instruction: 'Check glucose and ketones if supplies are available.' },
      { order: 3, instruction: 'Follow the persons emergency diabetes plan.' },
    ],
    warnings: ['Vomiting and deep breathing may indicate ketoacidosis.'],
    whenToCallEmergency: ['Call if vomiting, confusion, or severe weakness appears.'],
    doNot: ['Do not delay care waiting for numbers to normalize.'],
  },
  {
    id: 'dehydration-severe',
    category: 'heat-stroke',
    titleKey: 'Severe Dehydration',
    descriptionKey: 'Rapid first aid for significant fluid loss.',
    icon: '💧',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'Move to a cool place and have the person rest.' },
      { order: 2, instruction: 'Give small, frequent sips of oral rehydration solution.' },
      { order: 3, instruction: 'Monitor for confusion, dizziness, and reduced urination.' },
    ],
    warnings: ['Severe dehydration can progress to shock.'],
    whenToCallEmergency: ['Call if mental status changes or fluids cannot be kept down.'],
    doNot: ['Do not give alcohol or very sugary drinks.'],
  },
  {
    id: 'heat-exhaustion',
    category: 'heat-stroke',
    titleKey: 'Heat Exhaustion',
    descriptionKey: 'Cool and rehydrate safely before heat stroke develops.',
    icon: '🌡️',
    severity: 'moderate',
    steps: [
      { order: 1, instruction: 'Move to shade or air conditioning immediately.' },
      { order: 2, instruction: 'Loosen clothing and cool skin with damp cloths.' },
      { order: 3, instruction: 'Give cool water slowly if fully alert.' },
    ],
    warnings: ['Heat exhaustion may become heat stroke if untreated.'],
    whenToCallEmergency: ['Call if symptoms worsen or do not improve within 30 minutes.'],
    doNot: ['Do not resume activity the same day.'],
    relatedCards: ['heat-stroke'],
  },
  {
    id: 'sunburn',
    category: 'burns',
    titleKey: 'Sunburn',
    descriptionKey: 'First aid for mild to moderate sunburn.',
    icon: '☀️',
    severity: 'minor',
    steps: [
      { order: 1, instruction: 'Get out of direct sun and cool the skin.' },
      { order: 2, instruction: 'Apply fragrance free moisturizer or aloe gel.' },
      { order: 3, instruction: 'Drink extra fluids and monitor for blistering.' },
    ],
    warnings: ['Large blistering burns need medical review.'],
    whenToCallEmergency: ['Call for confusion, fever, or dehydration signs.'],
    doNot: ['Do not pop blisters.'],
  },
  {
    id: 'chemical-burn-skin',
    category: 'burns',
    titleKey: 'Chemical Burn on Skin',
    descriptionKey: 'Decontaminate skin burns caused by household or industrial chemicals.',
    icon: '🧪',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'Brush off dry chemicals and remove contaminated clothing.' },
      { order: 2, instruction: 'Flush skin with cool running water for at least 20 minutes.' },
      { order: 3, instruction: 'Cover loosely with a clean non stick dressing.' },
    ],
    warnings: ['Some chemicals continue damaging tissue after exposure.'],
    whenToCallEmergency: ['Call immediately for large area exposure or persistent pain.'],
    doNot: ['Do not neutralize with another chemical.'],
  },
  {
    id: 'electrical-burn',
    category: 'burns',
    titleKey: 'Electrical Burn',
    descriptionKey: 'Manage electric shock injuries safely.',
    icon: '⚡',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'Turn off power source before touching the person.' },
      { order: 2, instruction: 'Call emergency services and assess breathing.' },
      { order: 3, instruction: 'Cover visible burns with clean dry dressing.' },
    ],
    warnings: ['Internal injury may be severe even with small skin burns.'],
    whenToCallEmergency: ['Always call after an electrical injury.'],
    doNot: ['Do not touch the person until power is confirmed off.'],
  },
  {
    id: 'eye-chemical-splash',
    category: 'burns',
    titleKey: 'Chemical Splash in Eye',
    descriptionKey: 'Emergency eye irrigation steps.',
    icon: '👁️',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'Start rinsing the eye with clean water immediately.' },
      { order: 2, instruction: 'Keep eyelids open and flush continuously for 20 minutes.' },
      { order: 3, instruction: 'Seek urgent medical care while irrigation continues.' },
    ],
    warnings: ['Every second matters in eye chemical injuries.'],
    whenToCallEmergency: ['Call for immediate emergency transport if pain or vision changes persist.'],
    doNot: ['Do not rub the eye.'],
  },
  {
    id: 'eye-foreign-object',
    category: 'burns',
    titleKey: 'Object in Eye',
    descriptionKey: 'First aid for dust, grit, or small debris in the eye.',
    icon: '👀',
    severity: 'moderate',
    steps: [
      { order: 1, instruction: 'Ask the person to blink and tear naturally.' },
      { order: 2, instruction: 'Rinse gently with clean water or saline.' },
      { order: 3, instruction: 'Cover eye lightly if discomfort remains.' },
    ],
    warnings: ['Embedded objects need emergency specialist care.'],
    whenToCallEmergency: ['Call if pain is severe or vision is reduced.'],
    doNot: ['Do not use tweezers on the eyeball.'],
  },
  {
    id: 'splinter-removal',
    category: 'bites-stings',
    titleKey: 'Splinter Removal',
    descriptionKey: 'Safe removal of small superficial splinters.',
    icon: '🪵',
    severity: 'minor',
    steps: [
      { order: 1, instruction: 'Wash hands and clean the area with soap and water.' },
      { order: 2, instruction: 'Use clean tweezers to pull the splinter in entry direction.' },
      { order: 3, instruction: 'Clean again and apply a small bandage.' },
    ],
    warnings: ['Deep splinters can cause infection or nerve damage.'],
    whenToCallEmergency: ['Call if splinter is deep, near eye, or cannot be removed.'],
    doNot: ['Do not dig aggressively with unclean tools.'],
  },
  {
    id: 'tick-bite',
    category: 'bites-stings',
    titleKey: 'Tick Bite',
    descriptionKey: 'Proper tick removal to lower infection risk.',
    icon: '🕷️',
    severity: 'moderate',
    steps: [
      { order: 1, instruction: 'Use fine tipped tweezers to grasp tick near skin.' },
      { order: 2, instruction: 'Pull upward steadily without twisting.' },
      { order: 3, instruction: 'Clean bite area and hands thoroughly.' },
    ],
    warnings: ['Ticks can transmit serious infections.'],
    whenToCallEmergency: ['Call if fever, rash, or flu like symptoms develop.'],
    doNot: ['Do not burn or crush the tick on skin.'],
  },
  {
    id: 'dog-bite',
    category: 'bites-stings',
    titleKey: 'Dog Bite',
    descriptionKey: 'Immediate wound care after a dog bite.',
    icon: '🐶',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'Control bleeding with direct pressure.' },
      { order: 2, instruction: 'Rinse wound with running water for several minutes.' },
      { order: 3, instruction: 'Cover with clean dressing and seek medical care.' },
    ],
    warnings: ['Animal bites carry high infection risk including rabies.'],
    whenToCallEmergency: ['Call for deep wounds, heavy bleeding, or unknown vaccination status.'],
    doNot: ['Do not close a deep bite at home with glue or strips.'],
  },
  {
    id: 'cat-bite',
    category: 'bites-stings',
    titleKey: 'Cat Bite',
    descriptionKey: 'Fast cleaning and monitoring for puncture wound infection.',
    icon: '🐱',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'Wash the puncture thoroughly with soap and water.' },
      { order: 2, instruction: 'Apply clean dressing and elevate if swollen.' },
      { order: 3, instruction: 'Arrange same day medical review for antibiotics.' },
    ],
    warnings: ['Cat bites often become infected quickly.'],
    whenToCallEmergency: ['Call if redness spreads or fever appears.'],
    doNot: ['Do not ignore small puncture wounds.'],
  },
  {
    id: 'spider-bite',
    category: 'bites-stings',
    titleKey: 'Spider Bite',
    descriptionKey: 'General first aid for suspected spider bites.',
    icon: '🕸️',
    severity: 'moderate',
    steps: [
      { order: 1, instruction: 'Wash bite area and apply a cold pack.' },
      { order: 2, instruction: 'Keep the bitten limb elevated and still.' },
      { order: 3, instruction: 'Observe for severe pain or spreading symptoms.' },
    ],
    warnings: ['Some spider species can cause severe systemic effects.'],
    whenToCallEmergency: ['Call if severe pain, muscle cramps, or breathing issues occur.'],
    doNot: ['Do not cut or suck the wound.'],
  },
  {
    id: 'jellyfish-sting',
    category: 'bites-stings',
    titleKey: 'Jellyfish Sting',
    descriptionKey: 'Beach first aid for jellyfish stings.',
    icon: '🪼',
    severity: 'moderate',
    steps: [
      { order: 1, instruction: 'Rinse with seawater and remove tentacles with gloves or tweezers.' },
      { order: 2, instruction: 'Soak in hot water if available for pain control.' },
      { order: 3, instruction: 'Monitor for allergy symptoms and worsening pain.' },
    ],
    warnings: ['Large stings can trigger severe allergic reactions.'],
    whenToCallEmergency: ['Call for breathing difficulty, chest pain, or extensive stings.'],
    doNot: ['Do not rinse with fresh water right away.'],
  },
  {
    id: 'scorpion-sting',
    category: 'bites-stings',
    titleKey: 'Scorpion Sting',
    descriptionKey: 'Stabilize and monitor after a scorpion sting.',
    icon: '🦂',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'Wash sting site and apply a cool compress.' },
      { order: 2, instruction: 'Keep the person calm and limit movement.' },
      { order: 3, instruction: 'Contact poison services for region specific advice.' },
    ],
    warnings: ['Children can deteriorate quickly after venomous stings.'],
    whenToCallEmergency: ['Call for severe pain, drooling, twitching, or breathing changes.'],
    doNot: ['Do not apply a tourniquet.'],
  },
  {
    id: 'stingray-injury',
    category: 'bites-stings',
    titleKey: 'Stingray Injury',
    descriptionKey: 'Care for puncture wounds caused by stingray barbs.',
    icon: '🐟',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'Rinse wound and immerse in hot water for pain relief.' },
      { order: 2, instruction: 'Control bleeding and keep person still.' },
      { order: 3, instruction: 'Seek urgent medical evaluation for retained fragments.' },
    ],
    warnings: ['Retained barb fragments can cause infection and tissue injury.'],
    whenToCallEmergency: ['Call for deep puncture, severe bleeding, or chest or abdomen wound.'],
    doNot: ['Do not attempt deep barb removal at the beach.'],
  },
  {
    id: 'choking-self',
    category: 'choking',
    titleKey: 'Choking Alone',
    descriptionKey: 'Self rescue actions if no helper is available.',
    icon: '🧍',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'Call emergency services immediately if possible.' },
      { order: 2, instruction: 'Perform forceful self abdominal thrusts with fist.' },
      { order: 3, instruction: 'Press upper abdomen against a firm chair edge.' },
    ],
    warnings: ['Loss of consciousness can occur within minutes.'],
    whenToCallEmergency: ['Call if object does not clear immediately.'],
    doNot: ['Do not waste time trying to drink water.'],
  },
  {
    id: 'choking-child',
    category: 'choking',
    titleKey: 'Choking Child',
    descriptionKey: 'Respond safely to airway obstruction in children.',
    icon: '🧒',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'Confirm severe choking and call for help.' },
      { order: 2, instruction: 'Give age appropriate back blows and abdominal thrusts.' },
      { order: 3, instruction: 'Start CPR if child becomes unresponsive.' },
    ],
    warnings: ['Children decompensate rapidly during airway obstruction.'],
    whenToCallEmergency: ['Always call for persistent choking signs.'],
    doNot: ['Do not blind finger sweep the mouth.'],
    relatedCards: ['choking-infant', 'choking-adult'],
  },
  {
    id: 'cpr-child',
    category: 'cpr',
    titleKey: 'CPR for Children',
    descriptionKey: 'Basic CPR sequence for children from 1 year to puberty.',
    icon: '🫀',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'Check responsiveness and call emergency services.' },
      { order: 2, instruction: 'Give 30 compressions at one third chest depth.' },
      { order: 3, instruction: 'Give 2 rescue breaths and continue cycles.' },
    ],
    warnings: ['Use pediatric technique and depth to avoid injury.'],
    whenToCallEmergency: ['Call immediately for unresponsive child with absent normal breathing.'],
    doNot: ['Do not stop compressions for long pauses.'],
    relatedCards: ['cpr-adult'],
  },
  {
    id: 'aed-use',
    category: 'cpr',
    titleKey: 'AED Use Basics',
    descriptionKey: 'How to use an automated external defibrillator safely.',
    icon: '📟',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'Turn on AED and follow voice prompts.' },
      { order: 2, instruction: 'Place pads on bare chest as illustrated.' },
      { order: 3, instruction: 'Ensure nobody touches patient during analysis or shock.' },
    ],
    warnings: ['Immediate defibrillation greatly improves survival.'],
    whenToCallEmergency: ['Call if not already activated before AED use.'],
    doNot: ['Do not place pads over medication patches or wet skin.'],
    relatedCards: ['cpr-adult'],
  },
  {
    id: 'seizure-child-fever',
    category: 'seizures',
    titleKey: 'Febrile Seizure in Child',
    descriptionKey: 'Keep children safe during fever related seizure episodes.',
    icon: '🌡️',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'Place child on side and clear nearby hazards.' },
      { order: 2, instruction: 'Time the seizure and observe breathing.' },
      { order: 3, instruction: 'After seizure, cool gently and seek medical advice.' },
    ],
    warnings: ['First time febrile seizure requires clinical assessment.'],
    whenToCallEmergency: ['Call if seizure lasts longer than 5 minutes.'],
    doNot: ['Do not restrain the child or place objects in mouth.'],
  },
  {
    id: 'seizure-aftercare',
    category: 'seizures',
    titleKey: 'Post Seizure Care',
    descriptionKey: 'Support recovery safely after convulsions stop.',
    icon: '🛌',
    severity: 'moderate',
    steps: [
      { order: 1, instruction: 'Place person in recovery position and check breathing.' },
      { order: 2, instruction: 'Speak calmly and reassure as awareness returns.' },
      { order: 3, instruction: 'Document duration, triggers, and injuries.' },
    ],
    warnings: ['Injuries and recurrent seizures may occur in recovery phase.'],
    whenToCallEmergency: ['Call for repeated seizures or delayed awakening.'],
    doNot: ['Do not offer food until fully alert.'],
    relatedCards: ['seizures'],
  },
  {
    id: 'concussion-suspected',
    category: 'stroke',
    titleKey: 'Suspected Concussion',
    descriptionKey: 'Initial care after mild traumatic head injury.',
    icon: '🧠',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'Remove from activity and keep the person resting.' },
      { order: 2, instruction: 'Monitor for headache, vomiting, confusion, or drowsiness.' },
      { order: 3, instruction: 'Arrange prompt medical evaluation before return to activity.' },
    ],
    warnings: ['Symptoms can worsen over several hours.'],
    whenToCallEmergency: ['Call for repeated vomiting, severe headache, or behavior change.'],
    doNot: ['Do not allow immediate return to sport.'],
  },
  {
    id: 'head-injury-cut',
    category: 'bleeding',
    titleKey: 'Scalp Cut',
    descriptionKey: 'Manage scalp lacerations with direct pressure and observation.',
    icon: '🩹',
    severity: 'moderate',
    steps: [
      { order: 1, instruction: 'Apply firm direct pressure using clean cloth.' },
      { order: 2, instruction: 'Keep the person seated and calm.' },
      { order: 3, instruction: 'Check for signs of concussion while bleeding is controlled.' },
    ],
    warnings: ['Head wounds can bleed heavily even when small.'],
    whenToCallEmergency: ['Call if bleeding persists or head injury symptoms appear.'],
    doNot: ['Do not press on obvious skull fracture areas.'],
  },
  {
    id: 'knocked-out-tooth',
    category: 'fractures',
    titleKey: 'Knocked Out Tooth',
    descriptionKey: 'Emergency steps to improve chance of tooth reimplantation.',
    icon: '🦷',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'Handle tooth by the crown, not the root.' },
      { order: 2, instruction: 'Rinse briefly with saline or milk if dirty.' },
      { order: 3, instruction: 'Store tooth in milk and seek urgent dental care.' },
    ],
    warnings: ['Reimplantation success drops quickly over time.'],
    whenToCallEmergency: ['Call emergency dental services immediately.'],
    doNot: ['Do not scrub or dry the root surface.'],
  },
  {
    id: 'broken-nose',
    category: 'fractures',
    titleKey: 'Suspected Broken Nose',
    descriptionKey: 'Control bleeding and swelling after nasal trauma.',
    icon: '👃',
    severity: 'moderate',
    steps: [
      { order: 1, instruction: 'Apply cold pack to reduce swelling.' },
      { order: 2, instruction: 'Lean forward slightly if bleeding occurs.' },
      { order: 3, instruction: 'Arrange urgent medical assessment for deformity.' },
    ],
    warnings: ['Facial fractures may involve breathing obstruction.'],
    whenToCallEmergency: ['Call if breathing is difficult or heavy bleeding continues.'],
    doNot: ['Do not attempt to realign the nose.'],
  },
  {
    id: 'ankle-sprain',
    category: 'fractures',
    titleKey: 'Ankle Sprain',
    descriptionKey: 'Early care for ligament injury around the ankle.',
    icon: '🦶',
    severity: 'minor',
    steps: [
      { order: 1, instruction: 'Rest the ankle and avoid painful weight bearing.' },
      { order: 2, instruction: 'Apply cold pack and compression wrap.' },
      { order: 3, instruction: 'Elevate the ankle above heart level regularly.' },
    ],
    warnings: ['Severe sprains can hide fractures.'],
    whenToCallEmergency: ['Call if unable to walk four steps after injury.'],
    doNot: ['Do not use heat during the first day.'],
    relatedCards: ['fracture-limb'],
  },
  {
    id: 'wrist-sprain',
    category: 'fractures',
    titleKey: 'Wrist Sprain',
    descriptionKey: 'Simple stabilization for wrist soft tissue injuries.',
    icon: '✋',
    severity: 'minor',
    steps: [
      { order: 1, instruction: 'Rest and support wrist with a splint or wrap.' },
      { order: 2, instruction: 'Apply cold pack in short intervals.' },
      { order: 3, instruction: 'Elevate and monitor grip strength and sensation.' },
    ],
    warnings: ['Persistent pain may indicate scaphoid fracture.'],
    whenToCallEmergency: ['Call if numbness, deformity, or severe pain appears.'],
    doNot: ['Do not force wrist movement through pain.'],
  },
  {
    id: 'shoulder-dislocation',
    category: 'fractures',
    titleKey: 'Shoulder Dislocation',
    descriptionKey: 'Immobilize and transport for urgent reduction.',
    icon: '💪',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'Support arm in most comfortable position.' },
      { order: 2, instruction: 'Apply cold pack around shoulder.' },
      { order: 3, instruction: 'Transport for urgent medical reduction.' },
    ],
    warnings: ['Nerve and vessel injury can accompany dislocation.'],
    whenToCallEmergency: ['Call if hand becomes numb, pale, or cold.'],
    doNot: ['Do not attempt to pop shoulder back in place.'],
  },
  {
    id: 'knee-twist-injury',
    category: 'fractures',
    titleKey: 'Knee Twist Injury',
    descriptionKey: 'Protect and rest possible ligament or meniscus injury.',
    icon: '🦵',
    severity: 'moderate',
    steps: [
      { order: 1, instruction: 'Stop activity and keep weight off the knee.' },
      { order: 2, instruction: 'Apply cold compress and light compression.' },
      { order: 3, instruction: 'Use support and arrange medical assessment.' },
    ],
    warnings: ['Swelling and locking may indicate internal joint damage.'],
    whenToCallEmergency: ['Call if knee is deformed or cannot bear weight.'],
    doNot: ['Do not force full bending or twisting.'],
  },
  {
    id: 'lower-back-strain',
    category: 'fractures',
    titleKey: 'Lower Back Strain',
    descriptionKey: 'Initial care for sudden lower back muscle strain.',
    icon: '🧍‍♂️',
    severity: 'minor',
    steps: [
      { order: 1, instruction: 'Encourage gentle movement and avoid prolonged bed rest.' },
      { order: 2, instruction: 'Use cold or warm packs based on comfort.' },
      { order: 3, instruction: 'Monitor for weakness, numbness, or bladder changes.' },
    ],
    warnings: ['Neurologic symptoms require urgent evaluation.'],
    whenToCallEmergency: ['Call if leg weakness or loss of bladder control occurs.'],
    doNot: ['Do not lift heavy objects during acute pain.'],
  },
  {
    id: 'blisters-foot',
    category: 'burns',
    titleKey: 'Foot Blisters',
    descriptionKey: 'Prevent infection and reduce friction pain from walking blisters.',
    icon: '👟',
    severity: 'minor',
    steps: [
      { order: 1, instruction: 'Clean and dry the blister area gently.' },
      { order: 2, instruction: 'Cover with protective blister dressing.' },
      { order: 3, instruction: 'Reduce friction with proper socks and footwear.' },
    ],
    warnings: ['Diabetes increases risk of serious foot infection.'],
    whenToCallEmergency: ['Call if redness spreads or pus appears.'],
    doNot: ['Do not remove blister roof unless directed by a clinician.'],
  },
  {
    id: 'deep-cut-glass',
    category: 'bleeding',
    titleKey: 'Deep Cut from Glass',
    descriptionKey: 'Control bleeding and protect wound before professional care.',
    icon: '🪟',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'Apply direct pressure with sterile dressing.' },
      { order: 2, instruction: 'Elevate injured area if possible.' },
      { order: 3, instruction: 'Secure dressing and seek urgent medical care.' },
    ],
    warnings: ['Glass wounds may involve hidden tendon or vessel injury.'],
    whenToCallEmergency: ['Call if bleeding is heavy or spurting.'],
    doNot: ['Do not probe wound for fragments with fingers.'],
  },
  {
    id: 'embedded-object-wound',
    category: 'bleeding',
    titleKey: 'Embedded Object Wound',
    descriptionKey: 'Stabilize objects lodged in tissue until help arrives.',
    icon: '📌',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'Do not remove the embedded object.' },
      { order: 2, instruction: 'Apply pressure around wound, not on object.' },
      { order: 3, instruction: 'Stabilize object with bulky dressings.' },
    ],
    warnings: ['Removing object can trigger catastrophic bleeding.'],
    whenToCallEmergency: ['Call emergency services immediately.'],
    doNot: ['Do not attempt home extraction.'],
  },
  {
    id: 'amputated-finger',
    category: 'bleeding',
    titleKey: 'Amputated Finger',
    descriptionKey: 'Preserve amputated part while controlling bleeding.',
    icon: '🖐️',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'Control bleeding with pressure dressing.' },
      { order: 2, instruction: 'Wrap severed part in moist gauze and place in sealed bag.' },
      { order: 3, instruction: 'Keep bag cool on ice pack without direct ice contact.' },
    ],
    warnings: ['Rapid transport improves surgical reattachment outcomes.'],
    whenToCallEmergency: ['Call emergency services immediately.'],
    doNot: ['Do not place amputated tissue directly on ice.'],
  },
  {
    id: 'chest-pain-unknown',
    category: 'heart-attack',
    titleKey: 'Unknown Chest Pain',
    descriptionKey: 'Treat unexplained chest pain as potential emergency.',
    icon: '🚑',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'Stop activity and seat person comfortably.' },
      { order: 2, instruction: 'Call emergency services promptly.' },
      { order: 3, instruction: 'Monitor breathing and readiness for CPR.' },
    ],
    warnings: ['Chest pain can signal heart attack, embolism, or aortic emergency.'],
    whenToCallEmergency: ['Call for chest pain lasting more than 5 minutes.'],
    doNot: ['Do not let person drive themselves.'],
    relatedCards: ['heart-attack'],
  },
  {
    id: 'angina-episode',
    category: 'heart-attack',
    titleKey: 'Angina Episode',
    descriptionKey: 'Short term support for known angina symptoms.',
    icon: '💊',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'Have person stop and rest in seated position.' },
      { order: 2, instruction: 'Assist with prescribed nitroglycerin dose.' },
      { order: 3, instruction: 'Reassess pain after 5 minutes.' },
    ],
    warnings: ['Pain that does not improve may be a heart attack.'],
    whenToCallEmergency: ['Call if pain persists after one nitroglycerin dose.'],
    doNot: ['Do not exceed prescribed medication plan.'],
  },
  {
    id: 'mini-stroke-warning',
    category: 'stroke',
    titleKey: 'Mini Stroke Warning',
    descriptionKey: 'Transient stroke signs still require emergency care.',
    icon: '⏱️',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'Use FAST check and document symptom onset time.' },
      { order: 2, instruction: 'Call emergency services even if symptoms improve.' },
      { order: 3, instruction: 'Keep person resting and monitor neurologic status.' },
    ],
    warnings: ['Transient ischemic attacks can precede major stroke.'],
    whenToCallEmergency: ['Always call for sudden neurologic symptoms.'],
    doNot: ['Do not wait for symptoms to return.'],
    relatedCards: ['stroke'],
  },
  {
    id: 'confusion-possible-stroke',
    category: 'stroke',
    titleKey: 'Sudden Confusion and Speech Change',
    descriptionKey: 'Early stroke focused response for confusion and speech problems.',
    icon: '🗣️',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'Check face, arm strength, and speech quickly.' },
      { order: 2, instruction: 'Call emergency services and report possible stroke.' },
      { order: 3, instruction: 'Keep person safe, seated, and under observation.' },
    ],
    warnings: ['Delays reduce eligibility for clot busting treatment.'],
    whenToCallEmergency: ['Call immediately for sudden confusion or slurred speech.'],
    doNot: ['Do not give food, drink, or sedatives.'],
    relatedCards: ['stroke'],
  },
  {
    id: 'carbon-monoxide-exposure',
    category: 'poisoning',
    titleKey: 'Carbon Monoxide Exposure',
    descriptionKey: 'Evacuate and oxygenate after suspected carbon monoxide poisoning.',
    icon: '🏠',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'Move everyone to fresh air immediately.' },
      { order: 2, instruction: 'Call emergency services and fire department.' },
      { order: 3, instruction: 'Monitor for headache, confusion, and collapse.' },
    ],
    warnings: ['Carbon monoxide is odorless and rapidly life threatening.'],
    whenToCallEmergency: ['Always call emergency services for suspected exposure.'],
    doNot: ['Do not reenter building until declared safe.'],
  },
  {
    id: 'alcohol-poisoning',
    category: 'poisoning',
    titleKey: 'Alcohol Poisoning',
    descriptionKey: 'Emergency care while awaiting medical response.',
    icon: '🍺',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'Call emergency services for slow breathing or unresponsiveness.' },
      { order: 2, instruction: 'Place person on side in recovery position.' },
      { order: 3, instruction: 'Keep warm and monitor breathing continuously.' },
    ],
    warnings: ['Breathing can stop without warning in alcohol poisoning.'],
    whenToCallEmergency: ['Call for vomiting, seizures, or inability to wake.'],
    doNot: ['Do not leave the person alone to sleep it off.'],
  },
  {
    id: 'overdose-suspected',
    category: 'poisoning',
    titleKey: 'Suspected Drug Overdose',
    descriptionKey: 'Immediate response before emergency teams arrive.',
    icon: '💉',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'Call emergency services and provide location details.' },
      { order: 2, instruction: 'Administer naloxone if opioid overdose is suspected and available.' },
      { order: 3, instruction: 'Start rescue breathing or CPR if needed.' },
    ],
    warnings: ['Re-sedation can occur after naloxone wears off.'],
    whenToCallEmergency: ['Always call for suspected overdose.'],
    doNot: ['Do not delay calling while searching for exact substance.'],
  },
  {
    id: 'household-cleaner-ingestion',
    category: 'poisoning',
    titleKey: 'Household Cleaner Ingestion',
    descriptionKey: 'Protect airway and seek poison control guidance.',
    icon: '🧴',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'Call poison control or emergency services immediately.' },
      { order: 2, instruction: 'Rinse mouth gently if person is conscious.' },
      { order: 3, instruction: 'Keep product container available for responders.' },
    ],
    warnings: ['Corrosive cleaners can burn mouth and esophagus.'],
    whenToCallEmergency: ['Call immediately for pain, drooling, or vomiting.'],
    doNot: ['Do not induce vomiting unless instructed by professionals.'],
  },
  {
    id: 'frostbite',
    category: 'hypothermia',
    titleKey: 'Frostbite',
    descriptionKey: 'Rewarm frozen tissue safely and prevent further damage.',
    icon: '🧤',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'Move to warm shelter and remove wet clothing.' },
      { order: 2, instruction: 'Rewarm affected area in warm water around body temperature.' },
      { order: 3, instruction: 'Protect rewarmed tissue with loose sterile dressing.' },
    ],
    warnings: ['Severe frostbite can cause permanent tissue loss.'],
    whenToCallEmergency: ['Call for white, hard, numb skin or large affected area.'],
    doNot: ['Do not rub or massage frostbitten skin.'],
    relatedCards: ['hypothermia'],
  },
  {
    id: 'cold-water-immersion',
    category: 'hypothermia',
    titleKey: 'Cold Water Immersion',
    descriptionKey: 'Post rescue warming priorities after cold water exposure.',
    icon: '🧊',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'Handle person gently and remove from wet environment.' },
      { order: 2, instruction: 'Replace wet clothes with dry layers and insulation.' },
      { order: 3, instruction: 'Apply gradual rewarming to core and monitor breathing.' },
    ],
    warnings: ['Rapid movement can trigger dangerous heart rhythm changes.'],
    whenToCallEmergency: ['Always call for prolonged cold water exposure.'],
    doNot: ['Do not apply direct high heat to limbs first.'],
    relatedCards: ['hypothermia', 'drowning'],
  },
  {
    id: 'near-drowning-recovery',
    category: 'drowning',
    titleKey: 'Near Drowning Recovery',
    descriptionKey: 'Aftercare priorities when breathing returns after water rescue.',
    icon: '🏊',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'Keep person warm, resting, and under close observation.' },
      { order: 2, instruction: 'Check breathing, oxygen signs, and mental status repeatedly.' },
      { order: 3, instruction: 'Arrange emergency medical evaluation even if improved.' },
    ],
    warnings: ['Delayed breathing complications can occur hours later.'],
    whenToCallEmergency: ['Always call after any submersion event with symptoms.'],
    doNot: ['Do not assume full recovery without clinical assessment.'],
    relatedCards: ['drowning'],
  },
];

/**
 * Emergency phone numbers by country
 */
export const EMERGENCY_NUMBERS: EmergencyNumber[] = [
  {
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    numbers: { general: '911', poisonControl: '1-800-222-1222' },
  },
  {
    country: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    numbers: { general: '911', poisonControl: '1-800-268-9017' },
  },
  {
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    numbers: { general: '999', ambulance: '999', police: '999', fire: '999' },
  },
  {
    country: 'France',
    countryCode: 'FR',
    flag: '🇫🇷',
    numbers: { general: '112', ambulance: '15', police: '17', fire: '18', poisonControl: '01 40 05 48 48' },
  },
  {
    country: 'Germany',
    countryCode: 'DE',
    flag: '🇩🇪',
    numbers: { general: '112', police: '110', poisonControl: '030 19240' },
  },
  {
    country: 'Australia',
    countryCode: 'AU',
    flag: '🇦🇺',
    numbers: { general: '000', poisonControl: '13 11 26' },
  },
  {
    country: 'Japan',
    countryCode: 'JP',
    flag: '🇯🇵',
    numbers: { general: '119', police: '110', ambulance: '119', fire: '119' },
  },
  {
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    numbers: { general: '112', ambulance: '108', police: '100', fire: '101' },
  },
  {
    country: 'Brazil',
    countryCode: 'BR',
    flag: '🇧🇷',
    numbers: { general: '192', police: '190', ambulance: '192', fire: '193' },
  },
  {
    country: 'Mexico',
    countryCode: 'MX',
    flag: '🇲🇽',
    numbers: { general: '911', police: '911', ambulance: '911', fire: '911' },
  },
  {
    country: 'Spain',
    countryCode: 'ES',
    flag: '🇪🇸',
    numbers: { general: '112', police: '091', ambulance: '061' },
  },
  {
    country: 'Italy',
    countryCode: 'IT',
    flag: '🇮🇹',
    numbers: { general: '112', ambulance: '118', police: '113', fire: '115' },
  },
  {
    country: 'Netherlands',
    countryCode: 'NL',
    flag: '🇳🇱',
    numbers: { general: '112' },
  },
  {
    country: 'Belgium',
    countryCode: 'BE',
    flag: '🇧🇪',
    numbers: { general: '112', poisonControl: '070 245 245' },
  },
  {
    country: 'Switzerland',
    countryCode: 'CH',
    flag: '🇨🇭',
    numbers: { general: '112', ambulance: '144', police: '117', fire: '118', poisonControl: '145' },
  },
  {
    country: 'European Union',
    countryCode: 'EU',
    flag: '🇪🇺',
    numbers: { general: '112' },
  },
];

/**
 * Crisis helplines and mental health support
 */
export const HELPLINES: Helpline[] = [
  {
    id: 'suicide-prevention-us',
    nameKey: 'HELPLINES.SUICIDE_US.NAME',
    descriptionKey: 'HELPLINES.SUICIDE_US.DESC',
    phone: '988',
    website: 'https://988lifeline.org',
    available: '24/7',
    countries: ['US'],
    category: 'suicide-prevention',
    icon: '💙',
  },
  {
    id: 'crisis-text-us',
    nameKey: 'HELPLINES.CRISIS_TEXT_US.NAME',
    descriptionKey: 'HELPLINES.CRISIS_TEXT_US.DESC',
    phone: 'Text HOME to 741741',
    website: 'https://www.crisistextline.org',
    available: '24/7',
    countries: ['US', 'CA'],
    category: 'mental-health',
    icon: '💬',
  },
  {
    id: 'samaritans-uk',
    nameKey: 'HELPLINES.SAMARITANS_UK.NAME',
    descriptionKey: 'HELPLINES.SAMARITANS_UK.DESC',
    phone: '116 123',
    website: 'https://www.samaritans.org',
    available: '24/7',
    countries: ['GB', 'IE'],
    category: 'suicide-prevention',
    icon: '💚',
  },
  {
    id: 'sos-amitie-fr',
    nameKey: 'HELPLINES.SOS_AMITIE_FR.NAME',
    descriptionKey: 'HELPLINES.SOS_AMITIE_FR.DESC',
    phone: '09 72 39 40 50',
    website: 'https://www.sos-amitie.com',
    available: '24/7',
    countries: ['FR'],
    category: 'suicide-prevention',
    icon: '💜',
  },
  {
    id: 'telefonseelsorge-de',
    nameKey: 'HELPLINES.TELEFONSEELSORGE_DE.NAME',
    descriptionKey: 'HELPLINES.TELEFONSEELSORGE_DE.DESC',
    phone: '0800 111 0 111',
    website: 'https://www.telefonseelsorge.de',
    available: '24/7',
    countries: ['DE'],
    category: 'mental-health',
    icon: '🤝',
  },
  {
    id: 'kids-help-au',
    nameKey: 'HELPLINES.KIDS_HELP_AU.NAME',
    descriptionKey: 'HELPLINES.KIDS_HELP_AU.DESC',
    phone: '1800 55 1800',
    website: 'https://kidshelpline.com.au',
    available: '24/7',
    countries: ['AU'],
    category: 'mental-health',
    icon: '🧒',
  },
  {
    id: 'childline-uk',
    nameKey: 'HELPLINES.CHILDLINE_UK.NAME',
    descriptionKey: 'HELPLINES.CHILDLINE_UK.DESC',
    phone: '0800 1111',
    website: 'https://www.childline.org.uk',
    available: '24/7',
    countries: ['GB'],
    category: 'abuse',
    icon: '🛡️',
  },
  {
    id: 'international-crisis',
    nameKey: 'HELPLINES.INTERNATIONAL.NAME',
    descriptionKey: 'HELPLINES.INTERNATIONAL.DESC',
    phone: '',
    website: 'https://findahelpline.com',
    available: 'Varies',
    countries: [],
    category: 'general',
    icon: '🌍',
  },
];

/**
 * Category metadata for UI display
 */
export const FIRST_AID_CATEGORIES = [
  { id: 'cpr', labelKey: 'FIRST_AID.CATEGORY.CPR', icon: '❤️', color: '#ef4444' },
  { id: 'choking', labelKey: 'FIRST_AID.CATEGORY.CHOKING', icon: '🫁', color: '#f97316' },
  { id: 'burns', labelKey: 'FIRST_AID.CATEGORY.BURNS', icon: '🔥', color: '#eab308' },
  { id: 'allergic-reactions', labelKey: 'FIRST_AID.CATEGORY.ALLERGIC', icon: '🤧', color: '#84cc16' },
  { id: 'fractures', labelKey: 'FIRST_AID.CATEGORY.FRACTURES', icon: '🦴', color: '#06b6d4' },
  { id: 'bleeding', labelKey: 'FIRST_AID.CATEGORY.BLEEDING', icon: '🩸', color: '#dc2626' },
  { id: 'heart-attack', labelKey: 'FIRST_AID.CATEGORY.HEART', icon: '💔', color: '#be123c' },
  { id: 'stroke', labelKey: 'FIRST_AID.CATEGORY.STROKE', icon: '🧠', color: '#7c3aed' },
  { id: 'shock', labelKey: 'FIRST_AID.CATEGORY.SHOCK', icon: '😰', color: '#6366f1' },
  { id: 'seizures', labelKey: 'FIRST_AID.CATEGORY.SEIZURES', icon: '⚡', color: '#f59e0b' },
  { id: 'poisoning', labelKey: 'FIRST_AID.CATEGORY.POISONING', icon: '☠️', color: '#65a30d' },
  { id: 'hypothermia', labelKey: 'FIRST_AID.CATEGORY.HYPOTHERMIA', icon: '🥶', color: '#0ea5e9' },
  { id: 'heat-stroke', labelKey: 'FIRST_AID.CATEGORY.HEAT_STROKE', icon: '🥵', color: '#f43f5e' },
  { id: 'bites-stings', labelKey: 'FIRST_AID.CATEGORY.BITES', icon: '🐝', color: '#fbbf24' },
  { id: 'drowning', labelKey: 'FIRST_AID.CATEGORY.DROWNING', icon: '🌊', color: '#3b82f6' },
] as const;
