/**
 * First Aid Data
 * Comprehensive first aid procedures based on Red Cross and medical guidelines
 * 
 * DISCLAIMER: This information is for educational purposes only.
 * Always call emergency services in life-threatening situations.
 */

import { FirstAidCard, EmergencyNumber, Helpline } from './first-aid.types';

export const FIRST_AID_CARDS: FirstAidCard[] = [
  // =============== CPR ===============
  {
    id: 'cpr-adult',
    category: 'cpr',
    titleKey: 'FIRST_AID.CPR_ADULT.TITLE',
    descriptionKey: 'FIRST_AID.CPR_ADULT.DESC',
    icon: '❤️',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.CPR_ADULT.STEP_1', warning: 'FIRST_AID.CPR_ADULT.STEP_1_WARN' },
      { order: 2, instruction: 'FIRST_AID.CPR_ADULT.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.CPR_ADULT.STEP_3', tip: 'FIRST_AID.CPR_ADULT.STEP_3_TIP' },
      { order: 4, instruction: 'FIRST_AID.CPR_ADULT.STEP_4', duration: '30 compressions' },
      { order: 5, instruction: 'FIRST_AID.CPR_ADULT.STEP_5' },
      { order: 6, instruction: 'FIRST_AID.CPR_ADULT.STEP_6' },
    ],
    warnings: ['FIRST_AID.CPR_ADULT.WARN_1', 'FIRST_AID.CPR_ADULT.WARN_2'],
    whenToCallEmergency: ['FIRST_AID.CPR_ADULT.CALL_1'],
    doNot: ['FIRST_AID.CPR_ADULT.DONOT_1', 'FIRST_AID.CPR_ADULT.DONOT_2'],
    relatedCards: ['choking-adult', 'heart-attack'],
  },

  // =============== CHOKING ===============
  {
    id: 'choking-adult',
    category: 'choking',
    titleKey: 'FIRST_AID.CHOKING_ADULT.TITLE',
    descriptionKey: 'FIRST_AID.CHOKING_ADULT.DESC',
    icon: '🫁',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.CHOKING_ADULT.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.CHOKING_ADULT.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.CHOKING_ADULT.STEP_3', tip: 'FIRST_AID.CHOKING_ADULT.STEP_3_TIP' },
      { order: 4, instruction: 'FIRST_AID.CHOKING_ADULT.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.CHOKING_ADULT.STEP_5' },
    ],
    warnings: ['FIRST_AID.CHOKING_ADULT.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.CHOKING_ADULT.CALL_1'],
    doNot: ['FIRST_AID.CHOKING_ADULT.DONOT_1'],
    relatedCards: ['cpr-adult'],
  },
  {
    id: 'choking-infant',
    category: 'choking',
    titleKey: 'FIRST_AID.CHOKING_INFANT.TITLE',
    descriptionKey: 'FIRST_AID.CHOKING_INFANT.DESC',
    icon: '👶',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.CHOKING_INFANT.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.CHOKING_INFANT.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.CHOKING_INFANT.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.CHOKING_INFANT.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.CHOKING_INFANT.STEP_5' },
    ],
    warnings: ['FIRST_AID.CHOKING_INFANT.WARN_1', 'FIRST_AID.CHOKING_INFANT.WARN_2'],
    whenToCallEmergency: ['FIRST_AID.CHOKING_INFANT.CALL_1'],
    doNot: ['FIRST_AID.CHOKING_INFANT.DONOT_1'],
  },

  // =============== BURNS ===============
  {
    id: 'burns-minor',
    category: 'burns',
    titleKey: 'FIRST_AID.BURNS_MINOR.TITLE',
    descriptionKey: 'FIRST_AID.BURNS_MINOR.DESC',
    icon: '🔥',
    severity: 'moderate',
    steps: [
      { order: 1, instruction: 'FIRST_AID.BURNS_MINOR.STEP_1', duration: '10-20 minutes' },
      { order: 2, instruction: 'FIRST_AID.BURNS_MINOR.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.BURNS_MINOR.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.BURNS_MINOR.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.BURNS_MINOR.STEP_5' },
    ],
    warnings: ['FIRST_AID.BURNS_MINOR.WARN_1'],
    doNot: ['FIRST_AID.BURNS_MINOR.DONOT_1', 'FIRST_AID.BURNS_MINOR.DONOT_2', 'FIRST_AID.BURNS_MINOR.DONOT_3'],
    relatedCards: ['burns-severe'],
  },
  {
    id: 'burns-severe',
    category: 'burns',
    titleKey: 'FIRST_AID.BURNS_SEVERE.TITLE',
    descriptionKey: 'FIRST_AID.BURNS_SEVERE.DESC',
    icon: '🚨',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.BURNS_SEVERE.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.BURNS_SEVERE.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.BURNS_SEVERE.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.BURNS_SEVERE.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.BURNS_SEVERE.STEP_5' },
    ],
    warnings: ['FIRST_AID.BURNS_SEVERE.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.BURNS_SEVERE.CALL_1'],
    doNot: ['FIRST_AID.BURNS_SEVERE.DONOT_1', 'FIRST_AID.BURNS_SEVERE.DONOT_2', 'FIRST_AID.BURNS_SEVERE.DONOT_3'],
    relatedCards: ['burns-minor', 'shock'],
  },

  // =============== ALLERGIC REACTIONS ===============
  {
    id: 'allergic-mild',
    category: 'allergic-reactions',
    titleKey: 'FIRST_AID.ALLERGIC_MILD.TITLE',
    descriptionKey: 'FIRST_AID.ALLERGIC_MILD.DESC',
    icon: '🤧',
    severity: 'moderate',
    steps: [
      { order: 1, instruction: 'FIRST_AID.ALLERGIC_MILD.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.ALLERGIC_MILD.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.ALLERGIC_MILD.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.ALLERGIC_MILD.STEP_4' },
    ],
    warnings: ['FIRST_AID.ALLERGIC_MILD.WARN_1'],
    relatedCards: ['anaphylaxis'],
  },
  {
    id: 'anaphylaxis',
    category: 'allergic-reactions',
    titleKey: 'FIRST_AID.ANAPHYLAXIS.TITLE',
    descriptionKey: 'FIRST_AID.ANAPHYLAXIS.DESC',
    icon: '💉',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.ANAPHYLAXIS.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.ANAPHYLAXIS.STEP_2', tip: 'FIRST_AID.ANAPHYLAXIS.STEP_2_TIP' },
      { order: 3, instruction: 'FIRST_AID.ANAPHYLAXIS.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.ANAPHYLAXIS.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.ANAPHYLAXIS.STEP_5' },
    ],
    warnings: ['FIRST_AID.ANAPHYLAXIS.WARN_1', 'FIRST_AID.ANAPHYLAXIS.WARN_2'],
    whenToCallEmergency: ['FIRST_AID.ANAPHYLAXIS.CALL_1'],
    doNot: ['FIRST_AID.ANAPHYLAXIS.DONOT_1'],
    relatedCards: ['allergic-mild', 'shock'],
  },

  // =============== FRACTURES ===============
  {
    id: 'fracture-limb',
    category: 'fractures',
    titleKey: 'FIRST_AID.FRACTURE_LIMB.TITLE',
    descriptionKey: 'FIRST_AID.FRACTURE_LIMB.DESC',
    icon: '🦴',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'FIRST_AID.FRACTURE_LIMB.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.FRACTURE_LIMB.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.FRACTURE_LIMB.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.FRACTURE_LIMB.STEP_4', tip: 'FIRST_AID.FRACTURE_LIMB.STEP_4_TIP' },
      { order: 5, instruction: 'FIRST_AID.FRACTURE_LIMB.STEP_5' },
    ],
    warnings: ['FIRST_AID.FRACTURE_LIMB.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.FRACTURE_LIMB.CALL_1'],
    doNot: ['FIRST_AID.FRACTURE_LIMB.DONOT_1', 'FIRST_AID.FRACTURE_LIMB.DONOT_2'],
    relatedCards: ['fracture-spine', 'shock'],
  },
  {
    id: 'fracture-spine',
    category: 'fractures',
    titleKey: 'FIRST_AID.FRACTURE_SPINE.TITLE',
    descriptionKey: 'FIRST_AID.FRACTURE_SPINE.DESC',
    icon: '⚠️',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.FRACTURE_SPINE.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.FRACTURE_SPINE.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.FRACTURE_SPINE.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.FRACTURE_SPINE.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.FRACTURE_SPINE.STEP_5' },
    ],
    warnings: ['FIRST_AID.FRACTURE_SPINE.WARN_1', 'FIRST_AID.FRACTURE_SPINE.WARN_2'],
    whenToCallEmergency: ['FIRST_AID.FRACTURE_SPINE.CALL_1'],
    doNot: ['FIRST_AID.FRACTURE_SPINE.DONOT_1', 'FIRST_AID.FRACTURE_SPINE.DONOT_2', 'FIRST_AID.FRACTURE_SPINE.DONOT_3'],
    relatedCards: ['fracture-limb'],
  },

  // =============== BLEEDING ===============
  {
    id: 'bleeding-minor',
    category: 'bleeding',
    titleKey: 'FIRST_AID.BLEEDING_MINOR.TITLE',
    descriptionKey: 'FIRST_AID.BLEEDING_MINOR.DESC',
    icon: '🩹',
    severity: 'minor',
    steps: [
      { order: 1, instruction: 'FIRST_AID.BLEEDING_MINOR.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.BLEEDING_MINOR.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.BLEEDING_MINOR.STEP_3', duration: '10-15 minutes' },
      { order: 4, instruction: 'FIRST_AID.BLEEDING_MINOR.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.BLEEDING_MINOR.STEP_5' },
    ],
    doNot: ['FIRST_AID.BLEEDING_MINOR.DONOT_1'],
    relatedCards: ['bleeding-severe'],
  },
  {
    id: 'bleeding-severe',
    category: 'bleeding',
    titleKey: 'FIRST_AID.BLEEDING_SEVERE.TITLE',
    descriptionKey: 'FIRST_AID.BLEEDING_SEVERE.DESC',
    icon: '🩸',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.BLEEDING_SEVERE.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.BLEEDING_SEVERE.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.BLEEDING_SEVERE.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.BLEEDING_SEVERE.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.BLEEDING_SEVERE.STEP_5' },
    ],
    warnings: ['FIRST_AID.BLEEDING_SEVERE.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.BLEEDING_SEVERE.CALL_1'],
    doNot: ['FIRST_AID.BLEEDING_SEVERE.DONOT_1', 'FIRST_AID.BLEEDING_SEVERE.DONOT_2'],
    relatedCards: ['bleeding-minor', 'shock'],
  },

  // =============== HEART ATTACK ===============
  {
    id: 'heart-attack',
    category: 'heart-attack',
    titleKey: 'FIRST_AID.HEART_ATTACK.TITLE',
    descriptionKey: 'FIRST_AID.HEART_ATTACK.DESC',
    icon: '💔',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.HEART_ATTACK.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.HEART_ATTACK.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.HEART_ATTACK.STEP_3', tip: 'FIRST_AID.HEART_ATTACK.STEP_3_TIP' },
      { order: 4, instruction: 'FIRST_AID.HEART_ATTACK.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.HEART_ATTACK.STEP_5' },
    ],
    warnings: ['FIRST_AID.HEART_ATTACK.WARN_1', 'FIRST_AID.HEART_ATTACK.WARN_2'],
    whenToCallEmergency: ['FIRST_AID.HEART_ATTACK.CALL_1'],
    doNot: ['FIRST_AID.HEART_ATTACK.DONOT_1'],
    relatedCards: ['cpr-adult', 'stroke'],
  },

  // =============== STROKE ===============
  {
    id: 'stroke',
    category: 'stroke',
    titleKey: 'FIRST_AID.STROKE.TITLE',
    descriptionKey: 'FIRST_AID.STROKE.DESC',
    icon: '🧠',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.STROKE.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.STROKE.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.STROKE.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.STROKE.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.STROKE.STEP_5' },
    ],
    warnings: ['FIRST_AID.STROKE.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.STROKE.CALL_1'],
    doNot: ['FIRST_AID.STROKE.DONOT_1', 'FIRST_AID.STROKE.DONOT_2'],
    relatedCards: ['heart-attack'],
  },

  // =============== SHOCK ===============
  {
    id: 'shock',
    category: 'shock',
    titleKey: 'FIRST_AID.SHOCK.TITLE',
    descriptionKey: 'FIRST_AID.SHOCK.DESC',
    icon: '😰',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.SHOCK.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.SHOCK.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.SHOCK.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.SHOCK.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.SHOCK.STEP_5' },
    ],
    warnings: ['FIRST_AID.SHOCK.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.SHOCK.CALL_1'],
    doNot: ['FIRST_AID.SHOCK.DONOT_1', 'FIRST_AID.SHOCK.DONOT_2'],
    relatedCards: ['bleeding-severe', 'burns-severe'],
  },

  // =============== SEIZURES ===============
  {
    id: 'seizures',
    category: 'seizures',
    titleKey: 'FIRST_AID.SEIZURES.TITLE',
    descriptionKey: 'FIRST_AID.SEIZURES.DESC',
    icon: '⚡',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'FIRST_AID.SEIZURES.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.SEIZURES.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.SEIZURES.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.SEIZURES.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.SEIZURES.STEP_5' },
    ],
    warnings: ['FIRST_AID.SEIZURES.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.SEIZURES.CALL_1', 'FIRST_AID.SEIZURES.CALL_2'],
    doNot: ['FIRST_AID.SEIZURES.DONOT_1', 'FIRST_AID.SEIZURES.DONOT_2', 'FIRST_AID.SEIZURES.DONOT_3'],
  },

  // =============== POISONING ===============
  {
    id: 'poisoning',
    category: 'poisoning',
    titleKey: 'FIRST_AID.POISONING.TITLE',
    descriptionKey: 'FIRST_AID.POISONING.DESC',
    icon: '☠️',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.POISONING.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.POISONING.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.POISONING.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.POISONING.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.POISONING.STEP_5' },
    ],
    warnings: ['FIRST_AID.POISONING.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.POISONING.CALL_1'],
    doNot: ['FIRST_AID.POISONING.DONOT_1', 'FIRST_AID.POISONING.DONOT_2', 'FIRST_AID.POISONING.DONOT_3'],
  },

  // =============== HYPOTHERMIA ===============
  {
    id: 'hypothermia',
    category: 'hypothermia',
    titleKey: 'FIRST_AID.HYPOTHERMIA.TITLE',
    descriptionKey: 'FIRST_AID.HYPOTHERMIA.DESC',
    icon: '🥶',
    severity: 'serious',
    steps: [
      { order: 1, instruction: 'FIRST_AID.HYPOTHERMIA.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.HYPOTHERMIA.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.HYPOTHERMIA.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.HYPOTHERMIA.STEP_4', tip: 'FIRST_AID.HYPOTHERMIA.STEP_4_TIP' },
      { order: 5, instruction: 'FIRST_AID.HYPOTHERMIA.STEP_5' },
    ],
    warnings: ['FIRST_AID.HYPOTHERMIA.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.HYPOTHERMIA.CALL_1'],
    doNot: ['FIRST_AID.HYPOTHERMIA.DONOT_1', 'FIRST_AID.HYPOTHERMIA.DONOT_2'],
    relatedCards: ['heat-stroke'],
  },

  // =============== HEAT STROKE ===============
  {
    id: 'heat-stroke',
    category: 'heat-stroke',
    titleKey: 'FIRST_AID.HEAT_STROKE.TITLE',
    descriptionKey: 'FIRST_AID.HEAT_STROKE.DESC',
    icon: '🥵',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.HEAT_STROKE.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.HEAT_STROKE.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.HEAT_STROKE.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.HEAT_STROKE.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.HEAT_STROKE.STEP_5' },
    ],
    warnings: ['FIRST_AID.HEAT_STROKE.WARN_1', 'FIRST_AID.HEAT_STROKE.WARN_2'],
    whenToCallEmergency: ['FIRST_AID.HEAT_STROKE.CALL_1'],
    doNot: ['FIRST_AID.HEAT_STROKE.DONOT_1', 'FIRST_AID.HEAT_STROKE.DONOT_2'],
    relatedCards: ['hypothermia'],
  },

  // =============== BITES & STINGS ===============
  {
    id: 'bee-sting',
    category: 'bites-stings',
    titleKey: 'FIRST_AID.BEE_STING.TITLE',
    descriptionKey: 'FIRST_AID.BEE_STING.DESC',
    icon: '🐝',
    severity: 'moderate',
    steps: [
      { order: 1, instruction: 'FIRST_AID.BEE_STING.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.BEE_STING.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.BEE_STING.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.BEE_STING.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.BEE_STING.STEP_5' },
    ],
    warnings: ['FIRST_AID.BEE_STING.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.BEE_STING.CALL_1'],
    doNot: ['FIRST_AID.BEE_STING.DONOT_1'],
    relatedCards: ['anaphylaxis', 'snake-bite'],
  },
  {
    id: 'snake-bite',
    category: 'bites-stings',
    titleKey: 'FIRST_AID.SNAKE_BITE.TITLE',
    descriptionKey: 'FIRST_AID.SNAKE_BITE.DESC',
    icon: '🐍',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.SNAKE_BITE.STEP_1' },
      { order: 2, instruction: 'FIRST_AID.SNAKE_BITE.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.SNAKE_BITE.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.SNAKE_BITE.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.SNAKE_BITE.STEP_5' },
    ],
    warnings: ['FIRST_AID.SNAKE_BITE.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.SNAKE_BITE.CALL_1'],
    doNot: ['FIRST_AID.SNAKE_BITE.DONOT_1', 'FIRST_AID.SNAKE_BITE.DONOT_2', 'FIRST_AID.SNAKE_BITE.DONOT_3'],
    relatedCards: ['bee-sting', 'shock'],
  },

  // =============== DROWNING ===============
  {
    id: 'drowning',
    category: 'drowning',
    titleKey: 'FIRST_AID.DROWNING.TITLE',
    descriptionKey: 'FIRST_AID.DROWNING.DESC',
    icon: '🌊',
    severity: 'critical',
    steps: [
      { order: 1, instruction: 'FIRST_AID.DROWNING.STEP_1', warning: 'FIRST_AID.DROWNING.STEP_1_WARN' },
      { order: 2, instruction: 'FIRST_AID.DROWNING.STEP_2' },
      { order: 3, instruction: 'FIRST_AID.DROWNING.STEP_3' },
      { order: 4, instruction: 'FIRST_AID.DROWNING.STEP_4' },
      { order: 5, instruction: 'FIRST_AID.DROWNING.STEP_5' },
    ],
    warnings: ['FIRST_AID.DROWNING.WARN_1'],
    whenToCallEmergency: ['FIRST_AID.DROWNING.CALL_1'],
    doNot: ['FIRST_AID.DROWNING.DONOT_1'],
    relatedCards: ['cpr-adult', 'hypothermia'],
  },
];

/**
 * Emergency phone numbers by country
 */
export const EMERGENCY_NUMBERS: EmergencyNumber[] = [
  {
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    numbers: { general: '911', poisonControl: '1-800-222-1222' },
  },
  {
    country: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    numbers: { general: '911', poisonControl: '1-800-268-9017' },
  },
  {
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    numbers: { general: '999', ambulance: '999', police: '999', fire: '999' },
  },
  {
    country: 'France',
    countryCode: 'FR',
    flag: '🇫🇷',
    numbers: { general: '112', ambulance: '15', police: '17', fire: '18', poisonControl: '01 40 05 48 48' },
  },
  {
    country: 'Germany',
    countryCode: 'DE',
    flag: '🇩🇪',
    numbers: { general: '112', police: '110', poisonControl: '030 19240' },
  },
  {
    country: 'Australia',
    countryCode: 'AU',
    flag: '🇦🇺',
    numbers: { general: '000', poisonControl: '13 11 26' },
  },
  {
    country: 'Japan',
    countryCode: 'JP',
    flag: '🇯🇵',
    numbers: { general: '119', police: '110', ambulance: '119', fire: '119' },
  },
  {
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    numbers: { general: '112', ambulance: '108', police: '100', fire: '101' },
  },
  {
    country: 'Brazil',
    countryCode: 'BR',
    flag: '🇧🇷',
    numbers: { general: '192', police: '190', ambulance: '192', fire: '193' },
  },
  {
    country: 'Mexico',
    countryCode: 'MX',
    flag: '🇲🇽',
    numbers: { general: '911', police: '911', ambulance: '911', fire: '911' },
  },
  {
    country: 'Spain',
    countryCode: 'ES',
    flag: '🇪🇸',
    numbers: { general: '112', police: '091', ambulance: '061' },
  },
  {
    country: 'Italy',
    countryCode: 'IT',
    flag: '🇮🇹',
    numbers: { general: '112', ambulance: '118', police: '113', fire: '115' },
  },
  {
    country: 'Netherlands',
    countryCode: 'NL',
    flag: '🇳🇱',
    numbers: { general: '112' },
  },
  {
    country: 'Belgium',
    countryCode: 'BE',
    flag: '🇧🇪',
    numbers: { general: '112', poisonControl: '070 245 245' },
  },
  {
    country: 'Switzerland',
    countryCode: 'CH',
    flag: '🇨🇭',
    numbers: { general: '112', ambulance: '144', police: '117', fire: '118', poisonControl: '145' },
  },
  {
    country: 'European Union',
    countryCode: 'EU',
    flag: '🇪🇺',
    numbers: { general: '112' },
  },
];

/**
 * Crisis helplines and mental health support
 */
export const HELPLINES: Helpline[] = [
  {
    id: 'suicide-prevention-us',
    nameKey: 'HELPLINES.SUICIDE_US.NAME',
    descriptionKey: 'HELPLINES.SUICIDE_US.DESC',
    phone: '988',
    website: 'https://988lifeline.org',
    available: '24/7',
    countries: ['US'],
    category: 'suicide-prevention',
    icon: '💙',
  },
  {
    id: 'crisis-text-us',
    nameKey: 'HELPLINES.CRISIS_TEXT_US.NAME',
    descriptionKey: 'HELPLINES.CRISIS_TEXT_US.DESC',
    phone: 'Text HOME to 741741',
    website: 'https://www.crisistextline.org',
    available: '24/7',
    countries: ['US', 'CA'],
    category: 'mental-health',
    icon: '💬',
  },
  {
    id: 'samaritans-uk',
    nameKey: 'HELPLINES.SAMARITANS_UK.NAME',
    descriptionKey: 'HELPLINES.SAMARITANS_UK.DESC',
    phone: '116 123',
    website: 'https://www.samaritans.org',
    available: '24/7',
    countries: ['GB', 'IE'],
    category: 'suicide-prevention',
    icon: '💚',
  },
  {
    id: 'sos-amitie-fr',
    nameKey: 'HELPLINES.SOS_AMITIE_FR.NAME',
    descriptionKey: 'HELPLINES.SOS_AMITIE_FR.DESC',
    phone: '09 72 39 40 50',
    website: 'https://www.sos-amitie.com',
    available: '24/7',
    countries: ['FR'],
    category: 'suicide-prevention',
    icon: '💜',
  },
  {
    id: 'telefonseelsorge-de',
    nameKey: 'HELPLINES.TELEFONSEELSORGE_DE.NAME',
    descriptionKey: 'HELPLINES.TELEFONSEELSORGE_DE.DESC',
    phone: '0800 111 0 111',
    website: 'https://www.telefonseelsorge.de',
    available: '24/7',
    countries: ['DE'],
    category: 'mental-health',
    icon: '🤝',
  },
  {
    id: 'kids-help-au',
    nameKey: 'HELPLINES.KIDS_HELP_AU.NAME',
    descriptionKey: 'HELPLINES.KIDS_HELP_AU.DESC',
    phone: '1800 55 1800',
    website: 'https://kidshelpline.com.au',
    available: '24/7',
    countries: ['AU'],
    category: 'mental-health',
    icon: '🧒',
  },
  {
    id: 'childline-uk',
    nameKey: 'HELPLINES.CHILDLINE_UK.NAME',
    descriptionKey: 'HELPLINES.CHILDLINE_UK.DESC',
    phone: '0800 1111',
    website: 'https://www.childline.org.uk',
    available: '24/7',
    countries: ['GB'],
    category: 'abuse',
    icon: '🛡️',
  },
  {
    id: 'international-crisis',
    nameKey: 'HELPLINES.INTERNATIONAL.NAME',
    descriptionKey: 'HELPLINES.INTERNATIONAL.DESC',
    phone: '',
    website: 'https://findahelpline.com',
    available: 'Varies',
    countries: [],
    category: 'general',
    icon: '🌍',
  },
];

/**
 * Category metadata for UI display
 */
export const FIRST_AID_CATEGORIES = [
  { id: 'cpr', labelKey: 'FIRST_AID.CATEGORY.CPR', icon: '❤️', color: '#ef4444' },
  { id: 'choking', labelKey: 'FIRST_AID.CATEGORY.CHOKING', icon: '🫁', color: '#f97316' },
  { id: 'burns', labelKey: 'FIRST_AID.CATEGORY.BURNS', icon: '🔥', color: '#eab308' },
  { id: 'allergic-reactions', labelKey: 'FIRST_AID.CATEGORY.ALLERGIC', icon: '🤧', color: '#84cc16' },
  { id: 'fractures', labelKey: 'FIRST_AID.CATEGORY.FRACTURES', icon: '🦴', color: '#06b6d4' },
  { id: 'bleeding', labelKey: 'FIRST_AID.CATEGORY.BLEEDING', icon: '🩸', color: '#dc2626' },
  { id: 'heart-attack', labelKey: 'FIRST_AID.CATEGORY.HEART', icon: '💔', color: '#be123c' },
  { id: 'stroke', labelKey: 'FIRST_AID.CATEGORY.STROKE', icon: '🧠', color: '#7c3aed' },
  { id: 'shock', labelKey: 'FIRST_AID.CATEGORY.SHOCK', icon: '😰', color: '#6366f1' },
  { id: 'seizures', labelKey: 'FIRST_AID.CATEGORY.SEIZURES', icon: '⚡', color: '#f59e0b' },
  { id: 'poisoning', labelKey: 'FIRST_AID.CATEGORY.POISONING', icon: '☠️', color: '#65a30d' },
  { id: 'hypothermia', labelKey: 'FIRST_AID.CATEGORY.HYPOTHERMIA', icon: '🥶', color: '#0ea5e9' },
  { id: 'heat-stroke', labelKey: 'FIRST_AID.CATEGORY.HEAT_STROKE', icon: '🥵', color: '#f43f5e' },
  { id: 'bites-stings', labelKey: 'FIRST_AID.CATEGORY.BITES', icon: '🐝', color: '#fbbf24' },
  { id: 'drowning', labelKey: 'FIRST_AID.CATEGORY.DROWNING', icon: '🌊', color: '#3b82f6' },
] as const;
